(function(c){String.prototype.trim===c&&(String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")});Array.prototype.reduce===c&&(Array.prototype.reduce=function(l){if(void 0===this||null===this)throw new TypeError;var j=Object(this),f=j.length>>>0,a=0,b;if("function"!=typeof l)throw new TypeError;if(0==f&&1==arguments.length)throw new TypeError;if(2<=arguments.length)b=arguments[1];else{do{if(a in j){b=j[a++];break}if(++a>=f)throw new TypeError;}while(1)}for(;a<f;)a in j&&(b=l.call(c,
b,j[a],a,j)),a++;return b})})();
var Zepto=function(){function c(d){return null==d?String(d):W[O.call(d)]||"object"}function l(d){return"function"==c(d)}function j(d){return null!=d&&d==d.window}function f(d){return null!=d&&d.nodeType==d.DOCUMENT_NODE}function a(d){return"object"==c(d)}function b(d){return a(d)&&!j(d)&&d.__proto__==Object.prototype}function e(d){return d instanceof Array}function h(d){return"number"==typeof d.length}function k(d){return d.replace(/::/g,"/").replace(/([A-Z]+)([A-Z][a-z])/g,"$1_$2").replace(/([a-z\d])([A-Z])/g,
"$1_$2").replace(/_/g,"-").toLowerCase()}function g(d){return d in K?K[d]:K[d]=RegExp("(^|\\s)"+d+"(\\s|$)")}function r(d){return"children"in d?G.call(d.children):m.map(d.childNodes,function(d){if(1==d.nodeType)return d})}function q(d,a,c){for(v in a)c&&(b(a[v])||e(a[v]))?(b(a[v])&&!b(d[v])&&(d[v]={}),e(a[v])&&!e(d[v])&&(d[v]=[]),q(d[v],a[v],c)):a[v]!==t&&(d[v]=a[v])}function u(d,a){return a===t?m(d):m(d).filter(a)}function D(d,a,b,c){return l(a)?a.call(d,b,c):a}function x(d,a){var b=d.className,
c=b&&b.baseVal!==t;if(a===t)return c?b.baseVal:b;c?b.baseVal=a:d.className=a}function J(d){var a;try{return d?"true"==d||("false"==d?!1:"null"==d?null:isNaN(a=Number(d))?/^[\[\{]/.test(d)?m.parseJSON(d):d:a):d}catch(b){return d}}function I(d,a){a(d);for(var b in d.childNodes)I(d.childNodes[b],a)}var t,v,m,B,p=[],G=p.slice,w=p.filter,E=window.document,L={},K={},P=E.defaultView.getComputedStyle,X={"column-count":1,columns:1,"font-weight":1,"line-height":1,opacity:1,"z-index":1,zoom:1},Y=/^\s*<(\w+|!)[^>]*>/,
Z=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ig,T=/^(?:body|html)$/i,aa="val css html text data width height offset".split(" "),d=E.createElement("table"),U=E.createElement("tr"),M={tr:E.createElement("tbody"),tbody:d,thead:d,tfoot:d,td:U,th:U,"*":E.createElement("div")},ca=/complete|loaded|interactive/,Q=/^\.([\w-]+)$/,da=/^#([\w-]*)$/,ba=/^[\w-]+$/,W={},O=W.toString,z={},R,S,V=E.createElement("div");return z.matches=function(d,a){if(!d||1!==d.nodeType)return!1;var b=
d.webkitMatchesSelector||d.mozMatchesSelector||d.oMatchesSelector||d.matchesSelector;if(b)return b.call(d,a);var c,b=d.parentNode,s=!b;return s&&(b=V).appendChild(d),c=~z.qsa(b,a).indexOf(d),s&&V.removeChild(d),c},R=function(d){return d.replace(/-+(.)?/g,function(d,a){return a?a.toUpperCase():""})},S=function(d){return w.call(d,function(a,b){return d.indexOf(a)==b})},z.fragment=function(d,a,c){d.replace&&(d=d.replace(Z,"<$1></$2>"));a===t&&(a=Y.test(d)&&RegExp.$1);a in M||(a="*");var e,s,C=M[a];return C.innerHTML=
""+d,s=m.each(G.call(C.childNodes),function(){C.removeChild(this)}),b(c)&&(e=m(s),m.each(c,function(d,s){-1<aa.indexOf(d)?e[d](s):e.attr(d,s)})),s},z.Z=function(d,a){return d=d||[],d.__proto__=m.fn,d.selector=a||"",d},z.isZ=function(d){return d instanceof z.Z},z.init=function(d,c){if(!d)return z.Z();if(l(d))return m(E).ready(d);if(z.isZ(d))return d;var f;if(e(d))f=w.call(d,function(d){return null!=d});else if(a(d))f=[b(d)?m.extend({},d):d],d=null;else if(Y.test(d))f=z.fragment(d.trim(),RegExp.$1,
c),d=null;else{if(c!==t)return m(c).find(d);f=z.qsa(E,d)}return z.Z(f,d)},m=function(d,a){return z.init(d,a)},m.extend=function(d){var a,b=G.call(arguments,1);return"boolean"==typeof d&&(a=d,d=b.shift()),b.forEach(function(b){q(d,b,a)}),d},z.qsa=function(d,a){var b;return f(d)&&da.test(a)?(b=d.getElementById(RegExp.$1))?[b]:[]:1!==d.nodeType&&9!==d.nodeType?[]:G.call(Q.test(a)?d.getElementsByClassName(RegExp.$1):ba.test(a)?d.getElementsByTagName(a):d.querySelectorAll(a))},m.contains=function(d,a){return d!==
a&&d.contains(a)},m.type=c,m.isFunction=l,m.isWindow=j,m.isArray=e,m.isPlainObject=b,m.isEmptyObject=function(d){for(var a in d)return!1;return!0},m.inArray=function(d,a,b){return p.indexOf.call(a,d,b)},m.camelCase=R,m.trim=function(d){return d.trim()},m.uuid=0,m.support={},m.expr={},m.map=function(d,a){var b,c=[],s;if(h(d))for(s=0;s<d.length;s++)b=a(d[s],s),null!=b&&c.push(b);else for(s in d)b=a(d[s],s),null!=b&&c.push(b);return 0<c.length?m.fn.concat.apply([],c):c},m.each=function(d,a){var b;if(h(d))for(b=
0;b<d.length&&!1!==a.call(d[b],b,d[b]);b++);else for(b in d)if(!1===a.call(d[b],b,d[b]))break;return d},m.grep=function(d,a){return w.call(d,a)},window.JSON&&(m.parseJSON=JSON.parse),m.each("Boolean Number String Function Array Date RegExp Object Error".split(" "),function(d,a){W["[object "+a+"]"]=a.toLowerCase()}),m.fn={forEach:p.forEach,reduce:p.reduce,push:p.push,sort:p.sort,indexOf:p.indexOf,concat:p.concat,map:function(d){return m(m.map(this,function(a,b){return d.call(a,b,a)}))},slice:function(){return m(G.apply(this,
arguments))},ready:function(d){return ca.test(E.readyState)?d(m):E.addEventListener("DOMContentLoaded",function(){d(m)},!1),this},get:function(d){return d===t?G.call(this):this[0<=d?d:d+this.length]},toArray:function(){return this.get()},size:function(){return this.length},remove:function(){return this.each(function(){null!=this.parentNode&&this.parentNode.removeChild(this)})},each:function(d){return p.every.call(this,function(a,b){return!1!==d.call(a,b,a)}),this},filter:function(d){return l(d)?this.not(this.not(d)):
m(w.call(this,function(a){return z.matches(a,d)}))},add:function(d,a){return m(S(this.concat(m(d,a))))},is:function(d){return 0<this.length&&z.matches(this[0],d)},not:function(d){var a=[];if(l(d)&&d.call!==t)this.each(function(b){d.call(this,b)||a.push(this)});else{var b="string"==typeof d?this.filter(d):h(d)&&l(d.item)?G.call(d):m(d);this.forEach(function(d){0>b.indexOf(d)&&a.push(d)})}return m(a)},has:function(d){return this.filter(function(){return a(d)?m.contains(this,d):m(this).find(d).size()})},
eq:function(d){return-1===d?this.slice(d):this.slice(d,+d+1)},first:function(){var d=this[0];return d&&!a(d)?d:m(d)},last:function(){var d=this[this.length-1];return d&&!a(d)?d:m(d)},find:function(d){var a,b=this;return"object"==typeof d?a=m(d).filter(function(){var d=this;return p.some.call(b,function(s){return m.contains(s,d)})}):1==this.length?a=m(z.qsa(this[0],d)):a=this.map(function(){return z.qsa(this,d)}),a},closest:function(d,a){var b=this[0],c=!1;for("object"==typeof d&&(c=m(d));b&&!(c?0<=
c.indexOf(b):z.matches(b,d));)b=b!==a&&!f(b)&&b.parentNode;return m(b)},parents:function(d){for(var a=[],b=this;0<b.length;)b=m.map(b,function(d){if((d=d.parentNode)&&!f(d)&&0>a.indexOf(d))return a.push(d),d});return u(a,d)},parent:function(d){return u(S(this.pluck("parentNode")),d)},children:function(d){return u(this.map(function(){return r(this)}),d)},contents:function(){return this.map(function(){return G.call(this.childNodes)})},siblings:function(d){return u(this.map(function(d,a){return w.call(r(a.parentNode),
function(d){return d!==a})}),d)},empty:function(){return this.each(function(){this.innerHTML=""})},pluck:function(d){return m.map(this,function(a){return a[d]})},show:function(){return this.each(function(){"none"==this.style.display&&(this.style.display=null);if("none"==P(this,"").getPropertyValue("display")){var d=this.style,a;a=this.nodeName;var b,c;a=(L[a]||(b=E.createElement(a),E.body.appendChild(b),c=P(b,"").getPropertyValue("display"),b.parentNode.removeChild(b),"none"==c&&(c="block"),L[a]=
c),L[a]);d.display=a}})},replaceWith:function(d){return this.before(d).remove()},wrap:function(d){var a=l(d);if(this[0]&&!a)var b=m(d).get(0),c=b.parentNode||1<this.length;return this.each(function(s){m(this).wrapAll(a?d.call(this,s):c?b.cloneNode(!0):b)})},wrapAll:function(d){if(this[0]){m(this[0]).before(d=m(d));for(var a;(a=d.children()).length;)d=a.first();m(d).append(this)}return this},wrapInner:function(d){var a=l(d);return this.each(function(b){var c=m(this),s=c.contents();b=a?d.call(this,
b):d;s.length?s.wrapAll(b):c.append(b)})},unwrap:function(){return this.parent().each(function(){m(this).replaceWith(m(this).children())}),this},clone:function(){return this.map(function(){return this.cloneNode(!0)})},hide:function(){return this.css("display","none")},toggle:function(d){return this.each(function(){var a=m(this);(d===t?"none"==a.css("display"):d)?a.show():a.hide()})},prev:function(d){return m(this.pluck("previousElementSibling")).filter(d||"*")},next:function(d){return m(this.pluck("nextElementSibling")).filter(d||
"*")},html:function(d){return d===t?0<this.length?this[0].innerHTML:null:this.each(function(a){var b=this.innerHTML;m(this).empty().append(D(this,d,a,b))})},text:function(d){return d===t?0<this.length?this[0].textContent:null:this.each(function(){this.textContent=d})},attr:function(d,b){var c;return"string"==typeof d&&b===t?0==this.length||1!==this[0].nodeType?t:"value"==d&&"INPUT"==this[0].nodeName?this.val():!(c=this[0].getAttribute(d))&&d in this[0]?this[0][d]:c:this.each(function(c){if(1===this.nodeType)if(a(d))for(v in d){c=
v;var s=d[v];null==s?this.removeAttribute(c):this.setAttribute(c,s)}else c=D(this,b,c,this.getAttribute(d)),null==c?this.removeAttribute(d):this.setAttribute(d,c)})},removeAttr:function(d){return this.each(function(){1===this.nodeType&&this.removeAttribute(d)})},prop:function(d,a){return a===t?this[0]&&this[0][d]:this.each(function(b){this[d]=D(this,a,b,this[d])})},data:function(d,a){var b=this.attr("data-"+k(d),a);return null!==b?J(b):t},val:function(d){return d===t?this[0]&&(this[0].multiple?m(this[0]).find("option").filter(function(){return this.selected}).pluck("value"):
this[0].value):this.each(function(a){this.value=D(this,d,a,this.value)})},offset:function(d){if(d)return this.each(function(a){var b=m(this);a=D(this,d,a,b.offset());var s=b.offsetParent().offset();a={top:a.top-s.top,left:a.left-s.left};"static"==b.css("position")&&(a.position="relative");b.css(a)});if(0==this.length)return null;var a=this[0].getBoundingClientRect();return{left:a.left+window.pageXOffset,top:a.top+window.pageYOffset,width:Math.round(a.width),height:Math.round(a.height)}},css:function(d,
a){if(2>arguments.length&&"string"==typeof d)return this[0]&&(this[0].style[R(d)]||P(this[0],"").getPropertyValue(d));var b="";if("string"==c(d))!a&&0!==a?this.each(function(){this.style.removeProperty(k(d))}):b=k(d)+":"+("number"==typeof a&&!X[k(d)]?a+"px":a);else for(v in d)!d[v]&&0!==d[v]?this.each(function(){this.style.removeProperty(k(v))}):b+=k(v)+":"+("number"==typeof d[v]&&!X[k(v)]?d[v]+"px":d[v])+";";return this.each(function(){this.style.cssText+=";"+b})},index:function(d){return d?this.indexOf(m(d)[0]):
this.parent().children().indexOf(this[0])},hasClass:function(d){return p.some.call(this,function(d){return this.test(x(d))},g(d))},addClass:function(d){return this.each(function(a){B=[];var b=x(this);D(this,d,a,b).split(/\s+/g).forEach(function(d){m(this).hasClass(d)||B.push(d)},this);B.length&&x(this,b+(b?" ":"")+B.join(" "))})},removeClass:function(d){return this.each(function(a){if(d===t)return x(this,"");B=x(this);D(this,d,a,B).split(/\s+/g).forEach(function(d){B=B.replace(g(d)," ")});x(this,
B.trim())})},toggleClass:function(d,a){return this.each(function(b){var c=m(this);D(this,d,b,x(this)).split(/\s+/g).forEach(function(d){(a===t?!c.hasClass(d):a)?c.addClass(d):c.removeClass(d)})})},scrollTop:function(){if(this.length)return"scrollTop"in this[0]?this[0].scrollTop:this[0].scrollY},position:function(){if(this.length){var d=this[0],a=this.offsetParent(),b=this.offset(),c=T.test(a[0].nodeName)?{top:0,left:0}:a.offset();return b.top-=parseFloat(m(d).css("margin-top"))||0,b.left-=parseFloat(m(d).css("margin-left"))||
0,c.top+=parseFloat(m(a[0]).css("border-top-width"))||0,c.left+=parseFloat(m(a[0]).css("border-left-width"))||0,{top:b.top-c.top,left:b.left-c.left}}},offsetParent:function(){return this.map(function(){for(var d=this.offsetParent||E.body;d&&!T.test(d.nodeName)&&"static"==m(d).css("position");)d=d.offsetParent;return d})}},m.fn.detach=m.fn.remove,["width","height"].forEach(function(d){m.fn[d]=function(a){var b,c=this[0],s=d.replace(/./,function(d){return d[0].toUpperCase()});return a===t?j(c)?c["inner"+
s]:f(c)?c.documentElement["offset"+s]:(b=this.offset())&&b[d]:this.each(function(b){c=m(this);c.css(d,D(this,a,b,c[d]()))})}}),["after","prepend","before","append"].forEach(function(d,a){var b=a%2;m.fn[d]=function(){var d,s=m.map(arguments,function(a){return d=c(a),"object"==d||"array"==d||null==a?a:z.fragment(a)}),C,e=1<this.length;return 1>s.length?this:this.each(function(d,c){C=b?c:c.parentNode;c=0==a?c.nextSibling:1==a?c.firstChild:2==a?c:null;s.forEach(function(d){if(e)d=d.cloneNode(!0);else if(!C)return m(d).remove();
I(C.insertBefore(d,c),function(d){null!=d.nodeName&&"SCRIPT"===d.nodeName.toUpperCase()&&(!d.type||"text/javascript"===d.type)&&!d.src&&window.eval.call(window,d.innerHTML)})})})};m.fn[b?d+"To":"insert"+(a?"Before":"After")]=function(a){return m(a)[d](this),this}}),z.Z.prototype=m.fn,z.uniq=S,z.deserializeValue=J,m.zepto=z,m}();window.Zepto=Zepto;"$"in window||(window.$=Zepto);
(function(c){function l(c){var f=this.os={},a=this.browser={},b=c.match(/WebKit\/([\d.]+)/),e=c.match(/(Android)\s+([\d.]+)/),h=c.match(/(iPad).*OS\s([\d_]+)/),k=!h&&c.match(/(iPhone\sOS)\s([\d_]+)/),g=c.match(/(webOS|hpwOS)[\s\/]([\d.]+)/),r=g&&c.match(/TouchPad/),q=c.match(/Kindle\/([\d.]+)/),u=c.match(/Silk\/([\d._]+)/),l=c.match(/(BlackBerry).*Version\/([\d.]+)/),x=c.match(/(BB10).*Version\/([\d.]+)/),J=c.match(/(RIM\sTablet\sOS)\s([\d.]+)/),I=c.match(/PlayBook/),t=c.match(/Chrome\/([\d.]+)/)||
c.match(/CriOS\/([\d.]+)/),v=c.match(/Firefox\/([\d.]+)/);if(a.webkit=!!b)a.version=b[1];e&&(f.android=!0,f.version=e[2]);k&&(f.ios=f.iphone=!0,f.version=k[2].replace(/_/g,"."));h&&(f.ios=f.ipad=!0,f.version=h[2].replace(/_/g,"."));g&&(f.webos=!0,f.version=g[2]);r&&(f.touchpad=!0);l&&(f.blackberry=!0,f.version=l[2]);x&&(f.bb10=!0,f.version=x[2]);J&&(f.rimtabletos=!0,f.version=J[2]);I&&(a.playbook=!0);q&&(f.kindle=!0,f.version=q[1]);u&&(a.silk=!0,a.version=u[1]);!u&&f.android&&c.match(/Kindle Fire/)&&
(a.silk=!0);t&&(a.chrome=!0,a.version=t[1]);v&&(a.firefox=!0,a.version=v[1]);f.tablet=!(!h&&!I&&!(e&&!c.match(/Mobile/)||v&&c.match(/Tablet/)));f.phone=!f.tablet&&!(!e&&!k&&!g&&!l&&!x&&!(t&&c.match(/Android/)||t&&c.match(/CriOS\/([\d.]+)/)||v&&c.match(/Mobile/)))}l.call(c,navigator.userAgent);c.__detect=l})(Zepto);
(function(c){function l(a){return a._zid||(a._zid=g++)}function j(a,b,c,e){b=f(b);if(b.ns)var h=RegExp("(?:^| )"+b.ns.replace(" "," .* ?")+"(?: |$)");return(k[l(a)]||[]).filter(function(a){return a&&(!b.e||a.e==b.e)&&(!b.ns||h.test(a.ns))&&(!c||l(a.fn)===l(c))&&(!e||a.sel==e)})}function f(a){a=(""+a).split(".");return{e:a[0],ns:a.slice(1).sort().join(" ")}}function a(a,b,e){"string"!=c.type(a)?c.each(a,e):a.split(/\s/).forEach(function(a){e(a,b)})}function b(b,e,h,g,j,r){var u=l(b),w=k[u]||(k[u]=
[]);a(e,h,function(a,e){var h=f(a);h.fn=e;h.sel=g;h.e in q&&(e=function(a){var b=a.relatedTarget;if(!b||b!==this&&!c.contains(this,b))return h.fn.apply(this,arguments)});h.del=j&&j(e,a);var k=h.del||e;h.proxy=function(a){var c=k.apply(b,[a].concat(a.data));return!1===c&&(a.preventDefault(),a.stopPropagation()),c};h.i=w.length;w.push(h);b.addEventListener(q[h.e]||h.e,h.proxy,h.del&&("focus"==h.e||"blur"==h.e)||!!r)})}function e(b,c,e,f,h){var g=l(b);a(c||"",e,function(a,c){j(b,a,c,f).forEach(function(a){delete k[g][a.i];
b.removeEventListener(q[a.e]||a.e,a.proxy,a.del&&("focus"==a.e||"blur"==a.e)||!!h)})})}function h(a){var b,e={originalEvent:a};for(b in a)!x.test(b)&&void 0!==a[b]&&(e[b]=a[b]);return c.each(J,function(b,c){e[b]=function(){return this[c]=u,a[b].apply(a,arguments)};e[c]=D}),e}var k={},g=1,r={},q={mouseenter:"mouseover",mouseleave:"mouseout"};r.click=r.mousedown=r.mouseup=r.mousemove="MouseEvents";c.event={add:b,remove:e};c.proxy=function(a,b){if(c.isFunction(a)){var e=function(){return a.apply(b,arguments)};
return e._zid=l(a),e}if("string"==typeof b)return c.proxy(a[b],a);throw new TypeError("expected function");};c.fn.bind=function(a,c){return this.each(function(){b(this,a,c)})};c.fn.unbind=function(a,b){return this.each(function(){e(this,a,b)})};c.fn.one=function(a,c){return this.each(function(f,h){b(this,a,c,null,function(a,b){return function(){var c=a.apply(h,arguments);return e(h,b,a),c}})})};var u=function(){return!0},D=function(){return!1},x=/^([A-Z]|layer[XY]$)/,J={preventDefault:"isDefaultPrevented",
stopImmediatePropagation:"isImmediatePropagationStopped",stopPropagation:"isPropagationStopped"};c.fn.delegate=function(a,e,f){return this.each(function(g,k){b(k,e,f,a,function(b){return function(e){var f,g=c(e.target).closest(a,k).get(0);if(g)return f=c.extend(h(e),{currentTarget:g,liveFired:k}),b.apply(g,[f].concat([].slice.call(arguments,1)))}})})};c.fn.undelegate=function(a,b,c){return this.each(function(){e(this,b,c,a)})};c.fn.live=function(a,b){return c(document.body).delegate(this.selector,
a,b),this};c.fn.die=function(a,b){return c(document.body).undelegate(this.selector,a,b),this};c.fn.on=function(a,b,e){return!b||c.isFunction(b)?this.bind(a,b||e):this.delegate(b,a,e)};c.fn.off=function(a,b,e){return!b||c.isFunction(b)?this.unbind(a,b||e):this.undelegate(b,a,e)};c.fn.trigger=function(a,b){if("string"==typeof a||c.isPlainObject(a))a=c.Event(a);var e=a;if(!("defaultPrevented"in e)){e.defaultPrevented=!1;var f=e.preventDefault;e.preventDefault=function(){this.defaultPrevented=!0;f.call(this)}}return a.data=
b,this.each(function(){"dispatchEvent"in this&&this.dispatchEvent(a)})};c.fn.triggerHandler=function(a,b){var e,f;return this.each(function(g,k){e=h("string"==typeof a?c.Event(a):a);e.data=b;e.target=k;c.each(j(k,a.type||a),function(a,b){f=b.proxy(e);if(e.isImmediatePropagationStopped())return!1})}),f};"focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select keydown keypress keyup error".split(" ").forEach(function(a){c.fn[a]=
function(b){return b?this.bind(a,b):this.trigger(a)}});["focus","blur"].forEach(function(a){c.fn[a]=function(b){return b?this.bind(a,b):this.each(function(){try{this[a]()}catch(b){}}),this}});c.Event=function(a,b){"string"!=typeof a&&(b=a,a=b.type);var c=document.createEvent(r[a]||"Events"),e=!0;if(b)for(var f in b)"bubbles"==f?e=!!b[f]:c[f]=b[f];return c.initEvent(a,e,!0,null,null,null,null,null,null,null,null,null,null,null,null),c.isDefaultPrevented=function(){return this.defaultPrevented},c}})(Zepto);
(function(c){function l(a,b,e,f){if(a.global)return a=b||u,e=c.Event(e),c(a).trigger(e,f),!e.defaultPrevented}function j(a,b){var c=b.context;if(!1===b.beforeSend.call(c,a,b)||!1===l(b,c,"ajaxBeforeSend",[a,b]))return!1;l(b,c,"ajaxSend",[a,b])}function f(a,c,e){var f=e.context;e.success.call(f,a,"success",c);l(e,f,"ajaxSuccess",[c,e,a]);b("success",c,e)}function a(a,c,e,f){var h=f.context;f.error.call(h,e,c,a);l(f,h,"ajaxError",[e,f,a]);b(c,e,f)}function b(a,b,e){var f=e.context;e.complete.call(f,
b,a);l(e,f,"ajaxComplete",[b,e]);e.global&&!--c.active&&l(e,null,"ajaxStop")}function e(){}function h(a){return a&&(a=a.split(";",2)[0]),a&&(a==m?"html":a==v?"json":I.test(a)?"script":t.test(a)&&"xml")||"text"}function k(a,b){return(a+"&"+b).replace(/[&?]{1,2}/,"?")}function g(a,b,e,f){var h=!c.isFunction(b);return{url:a,data:h?b:void 0,success:h?c.isFunction(e)?e:void 0:b,dataType:h?f||e:e}}function r(a,b,e,f){var h,g=c.isArray(b);c.each(b,function(b,k){h=c.type(k);f&&(b=e?f:f+"["+(g?"":b)+"]");
!f&&g?a.add(k.name,k.value):"array"==h||!e&&"object"==h?r(a,k,e,b):a.add(b,k)})}var q=0,u=window.document,D,x,J=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,I=/^(?:text|application)\/javascript/i,t=/^(?:text|application)\/xml/i,v="application/json",m="text/html",B=/^\s*$/;c.active=0;c.ajaxJSONP=function(b){if("type"in b){var h="jsonp"+ ++q,g=u.createElement("script"),k=function(){clearTimeout(m);c(g).remove();delete window[h]},r=function(c){k();if(!c||"timeout"==c)window[h]=e;a(null,c||"abort",
l,b)},l={abort:r},m;return!1===j(l,b)?(r("abort"),!1):(window[h]=function(a){k();f(a,l,b)},g.onerror=function(){r("error")},g.src=b.url.replace(/=\?/,"="+h),c("head").append(g),0<b.timeout&&(m=setTimeout(function(){r("timeout")},b.timeout)),l)}return c.ajax(b)};c.ajaxSettings={type:"GET",beforeSend:e,success:e,error:e,complete:e,context:null,global:!0,xhr:function(){return new window.XMLHttpRequest},accepts:{script:"text/javascript, application/javascript",json:v,xml:"application/xml, text/xml",html:m,
text:"text/plain"},crossDomain:!1,timeout:0,processData:!0,cache:!0};c.ajax=function(b){var g=c.extend({},b||{});for(D in c.ajaxSettings)void 0===g[D]&&(g[D]=c.ajaxSettings[D]);g.global&&0===c.active++&&l(g,null,"ajaxStart");g.crossDomain||(g.crossDomain=/^([\w-]+:)?\/\/([^\/]+)/.test(g.url)&&RegExp.$2!=window.location.host);g.url||(g.url=window.location.toString());g.processData&&g.data&&"string"!=c.type(g.data)&&(g.data=c.param(g.data,g.traditional));g.data&&(!g.type||"GET"==g.type.toUpperCase())&&
(g.url=k(g.url,g.data));!1===g.cache&&(g.url=k(g.url,"_="+Date.now()));var r=g.dataType;b=/=\?/.test(g.url);if("jsonp"==r||b)return b||(g.url=k(g.url,"callback=?")),c.ajaxJSONP(g);b=g.accepts[r];var q={},u=/^([\w-]+:)\/\//.test(g.url)?RegExp.$1:window.location.protocol,m=g.xhr(),p;g.crossDomain||(q["X-Requested-With"]="XMLHttpRequest");b&&(q.Accept=b,-1<b.indexOf(",")&&(b=b.split(",",2)[0]),m.overrideMimeType&&m.overrideMimeType(b));if(g.contentType||!1!==g.contentType&&g.data&&"GET"!=g.type.toUpperCase())q["Content-Type"]=
g.contentType||"application/x-www-form-urlencoded";g.headers=c.extend(q,g.headers||{});m.onreadystatechange=function(){if(4==m.readyState){m.onreadystatechange=e;clearTimeout(p);var b,k=!1;if(200<=m.status&&300>m.status||304==m.status||0==m.status&&"file:"==u){r=r||h(m.getResponseHeader("content-type"));b=m.responseText;try{"script"==r?(0,eval)(b):"xml"==r?b=m.responseXML:"json"==r&&(b=B.test(b)?null:c.parseJSON(b))}catch(j){k=j}k?a(k,"parsererror",m,g):f(b,m,g)}else a(null,m.status?"error":"abort",
m,g)}};m.open(g.type,g.url,"async"in g?g.async:!0);for(x in g.headers)m.setRequestHeader(x,g.headers[x]);return!1===j(m,g)?(m.abort(),!1):(0<g.timeout&&(p=setTimeout(function(){m.onreadystatechange=e;m.abort();a(null,"timeout",m,g)},g.timeout)),m.send(g.data?g.data:null),m)};c.get=function(a,b,e,f){return c.ajax(g.apply(null,arguments))};c.post=function(a,b,e,f){var h=g.apply(null,arguments);return h.type="POST",c.ajax(h)};c.getJSON=function(a,b,e){var f=g.apply(null,arguments);return f.dataType=
"json",c.ajax(f)};c.fn.load=function(a,b,e){if(!this.length)return this;var f=this,h=a.split(/\s/),k;a=g(a,b,e);var j=a.success;return 1<h.length&&(a.url=h[0],k=h[1]),a.success=function(a){f.html(k?c("<div>").html(a.replace(J,"")).find(k):a);j&&j.apply(f,arguments)},c.ajax(a),this};var p=encodeURIComponent;c.param=function(a,b){var c=[];return c.add=function(a,b){this.push(p(a)+"="+p(b))},r(c,a,b),c.join("&").replace(/%20/g,"+")}})(Zepto);
(function(c){c.fn.serializeArray=function(){var l=[],j;return c(Array.prototype.slice.call(this.get(0).elements)).each(function(){j=c(this);var f=j.attr("type");"fieldset"!=this.nodeName.toLowerCase()&&!this.disabled&&"submit"!=f&&"reset"!=f&&"button"!=f&&("radio"!=f&&"checkbox"!=f||this.checked)&&l.push({name:j.attr("name"),value:j.val()})}),l};c.fn.serialize=function(){var c=[];return this.serializeArray().forEach(function(j){c.push(encodeURIComponent(j.name)+"="+encodeURIComponent(j.value))}),
c.join("&")};c.fn.submit=function(l){l?this.bind("submit",l):this.length&&(l=c.Event("submit"),this.eq(0).trigger(l),l.defaultPrevented||this.get(0).submit());return this}})(Zepto);
(function(c,l){function j(a){return a.toLowerCase()}var f="",a,b=window.document.createElement("div"),e=/^((translate|rotate|scale)(X|Y|Z|3d)?|matrix(3d)?|perspective|skew(X|Y)?)$/i,h,k,g,r,q,u,D,x={};c.each({Webkit:"webkit",Moz:"",O:"o",ms:"MS"},function(c,e){if(b.style[c+"TransitionProperty"]!==l)return f="-"+j(c)+"-",a=e,!1});h=f+"transform";x[k=f+"transition-property"]=x[g=f+"transition-duration"]=x[r=f+"transition-timing-function"]=x[q=f+"animation-name"]=x[u=f+"animation-duration"]=x[D=f+"animation-timing-function"]=
"";c.fx={off:a===l&&b.style.transitionProperty===l,speeds:{_default:400,fast:200,slow:600},cssPrefix:f,transitionEnd:a?a+"TransitionEnd":j("TransitionEnd"),animationEnd:a?a+"AnimationEnd":j("AnimationEnd")};c.fn.animate=function(a,b,e,f){return c.isPlainObject(b)&&(e=b.easing,f=b.complete,b=b.duration),b&&(b=("number"==typeof b?b:c.fx.speeds[b]||c.fx.speeds._default)/1E3),this.anim(a,b,e,f)};c.fn.anim=function(a,b,f,v){var m,B={},p,G="",w=this,E,L=c.fx.transitionEnd;b===l&&(b=0.4);c.fx.off&&(b=0);
if("string"==typeof a)B[q]=a,B[u]=b+"s",B[D]=f||"linear",L=c.fx.animationEnd;else{p=[];for(m in a)e.test(m)?G+=m+"("+a[m]+") ":(B[m]=a[m],p.push(j(m.replace(/([a-z])([A-Z])/,"$1-$2"))));G&&(B[h]=G,p.push(h));0<b&&"object"==typeof a&&(B[k]=p.join(", "),B[g]=b+"s",B[r]=f||"linear")}return E=function(a){if("undefined"!=typeof a){if(a.target!==a.currentTarget)return;c(a.target).unbind(L,E)}c(this).css(x);v&&v.call(this)},0<b&&this.bind(L,E),this.size()&&this.get(0).clientLeft,this.css(B),0>=b&&setTimeout(function(){w.each(function(){E.call(this)})},
0),this};b=null})(Zepto);
(function(){function c(a){throw a;}function l(a){return function(){return a}}function j(j){function u(b,c,e,f,h){var g=[];b=d.j(function(){var b=c(e,h)||[];0<g.length&&(d.a.Ya(D(g),b),f&&d.r.K(f,a,[e,b,h]));g.splice(0,g.length);d.a.P(g,b)},a,{W:b,Ka:function(){return 0==g.length||!d.a.X(g[0])}});return{M:g,j:b.pa()?b:r}}function D(a){for(;a.length&&!d.a.X(a[0]);)a.splice(0,1);if(1<a.length){for(var b=a[0],c=a[a.length-1],e=[b];b!==c;){b=b.nextSibling;if(!b)return;e.push(b)}Array.prototype.splice.apply(a,[0,
a.length].concat(e))}return a}function x(d,a,b,c,e){var f=Math.min,h=Math.max,g=[],n,k=d.length,H,j=a.length,r=j-k||1,y=k+j+1,q,m,u;for(n=0;n<=k;n++){m=q;g.push(q=[]);u=f(j,n+r);for(H=h(0,n-1);H<=u;H++)q[H]=H?n?d[n-1]===a[H-1]?m[H-1]:f(m[H]||y,q[H-1]||y)+1:H+1:n+1}f=[];h=[];r=[];n=k;for(H=j;n||H;)j=g[n][H]-1,H&&j===g[n][H-1]?h.push(f[f.length]={status:b,value:a[--H],index:H}):n&&j===g[n-1][H]?r.push(f[f.length]={status:c,value:d[--n],index:n}):(f.push({status:"retained",value:a[--H]}),--n);if(h.length&&
r.length){d=10*k;var A;for(a=b=0;(e||a<d)&&(A=h[b]);b++){for(c=0;g=r[c];c++)if(A.value===g.value){A.moved=g.index;g.moved=A.index;r.splice(c,1);a=c=0;break}a+=c}}return f.reverse()}function J(s,e,F,h,g){g=g||{};var n=s&&I(s),n=n&&n.ownerDocument,k=g.templateEngine||A;d.za.vb(F,k,n);F=k.renderTemplate(F,h,g,n);("number"!=typeof F.length||0<F.length&&"number"!=typeof F[0].nodeType)&&c(Error("Template engine must return an array of DOM nodes"));n=b;switch(e){case "replaceChildren":d.e.N(s,F);n=f;break;
case "replaceNode":d.a.Ya(s,F);n=f;break;case "ignoreTargetNode":break;default:c(Error("Unknown renderMode: "+e))}n&&(t(F,h),g.afterRender&&d.r.K(g.afterRender,a,[F,h.$data]));return F}function I(d){return d.nodeType?d:0<d.length?d[0]:a}function t(a,b){if(a.length){var c=a[0],e=a[a.length-1];v(c,e,function(a){d.Da(b,a)});v(c,e,function(a){d.s.ib(a,[b])})}}function v(a,b,c){var e;for(b=d.e.nextSibling(b);a&&(e=a)!==b;)a=d.e.nextSibling(e),(1===e.nodeType||8===e.nodeType)&&c(e)}function m(a,b,e){a=
d.g.aa(a);for(var f=d.g.Q,h=0;h<a.length;h++){var g=a[h].key;if(f.hasOwnProperty(g)){var n=f[g];"function"===typeof n?(g=n(a[h].value))&&c(Error(g)):n||c(Error("This template engine does not support the '"+g+"' binding within its templates"))}}a="ko.__tr_ambtns(function($context,$element){return(function(){return{ "+d.g.ba(a)+" } })()})";return e.createJavaScriptEvaluatorBlock(a)+b}function B(b,e,f,h){function g(a){return function(){return j[a]}}function n(){return j}var k=0,j,y;d.j(function(){var a=
f&&f instanceof d.z?f:new d.z(d.a.d(f)),H=a.$data;h&&d.eb(b,a);if(j=("function"==typeof e?e(a,b):e)||d.J.instance.getBindings(b,a)){if(0===k){k=1;for(var q in j){var A=d.c[q];A&&8===b.nodeType&&!d.e.I[q]&&c(Error("The binding '"+q+"' cannot be used with virtual elements"));if(A&&"function"==typeof A.init&&(A=(0,A.init)(b,g(q),n,H,a))&&A.controlsDescendantBindings)y!==r&&c(Error("Multiple bindings ("+y+" and "+q+") are trying to control descendant bindings of the same element. You cannot use these bindings together on the same element.")),
y=q}k=2}if(2===k)for(q in j)(A=d.c[q])&&"function"==typeof A.update&&(0,A.update)(b,g(q),n,H,a)}},a,{W:b});return{Nb:y===r}}function p(b,c,e){var h=f,g=1===c.nodeType;g&&d.e.Ta(c);if(g&&e||d.J.instance.nodeHasBindings(c))h=B(c,a,b,e).Nb;h&&G(b,c,!g)}function G(a,b,c){for(var e=d.e.firstChild(b);b=e;)e=d.e.nextSibling(b),p(a,b,c)}function w(d,b){var c=E(d,b);return c?0<c.length?c[c.length-1].nextSibling:d.nextSibling:a}function E(d,b){for(var e=d,f=1,h=[];e=e.nextSibling;){if(L(e)&&(f--,0===f))return h;
h.push(e);K(e)&&f++}b||c(Error("Cannot find closing comment tag to match: "+d.nodeValue));return a}function L(a){return 8==a.nodeType&&(O?a.text:a.nodeValue).match(R)}function K(a){return 8==a.nodeType&&(O?a.text:a.nodeValue).match(z)}function P(d,b){for(var c=a;d!=c;)c=d,d=d.replace(da,function(a,d){return b[d]});return d}function X(){var a=[],b=[];this.save=function(c,e){var f=d.a.i(a,c);0<=f?b[f]=e:(a.push(c),b.push(e))};this.get=function(c){c=d.a.i(a,c);return 0<=c?b[c]:r}}function Y(d,b,c){function e(a){var h=
b(d[a]);switch(typeof h){case "boolean":case "number":case "string":case "function":f[a]=h;break;case "object":case "undefined":var g=c.get(h);f[a]=g!==r?g:Y(h,b,c)}}c=c||new X;d=b(d);if(!("object"==typeof d&&d!==a&&d!==r&&!(d instanceof Date)))return d;var f=d instanceof Array?[]:{};c.save(d,f);var h=d;if(h instanceof Array){for(var g=0;g<h.length;g++)e(g);"function"==typeof h.toJSON&&e("toJSON")}else for(g in h)e(g);return f}function Z(b,c){if(b)if(8==b.nodeType){var e=d.s.Ua(b.nodeValue);e!=a&&
c.push({sb:b,Fb:e})}else if(1==b.nodeType)for(var e=0,f=b.childNodes,h=f.length;e<h;e++)Z(f[e],c)}function T(a,c,e,h){d.c[a]={init:function(a){d.a.f.set(a,N,{});return{controlsDescendantBindings:f}},update:function(a,b,s,g,n){s=d.a.f.get(a,N);b=d.a.d(b());g=!e!==!b;var k=!s.Za;if(k||c||g!==s.qb)k&&(s.Za=d.a.Ia(d.e.childNodes(a),f)),g?(k||d.e.N(a,d.a.Ia(s.Za)),d.Ea(h?h(n,b):n,a)):d.e.Y(a),s.qb=g}};d.g.Q[a]=b;d.e.I[a]=f}function aa(b,c,e){e&&c!==d.k.q(b)&&d.k.T(b,c);c!==d.k.q(b)&&d.r.K(d.a.Ba,a,[b,
"change"])}var d="undefined"!==typeof j?j:{};d.b=function(a,b){for(var c=a.split("."),e=d,f=0;f<c.length-1;f++)e=e[c[f]];e[c[c.length-1]]=b};d.p=function(a,d,b){a[d]=b};d.version="2.2.1";d.b("version",d.version);d.a=new function(){function s(a,c){if("input"!==d.a.u(a)||!a.type||"click"!=c.toLowerCase())return b;var e=a.type;return"checkbox"==e||"radio"==e}var C=/^(\s|\u00A0)+|(\s|\u00A0)+$/g,F={},n={};F[/Firefox\/2/i.test(k.userAgent)?"KeyboardEvent":"UIEvents"]=["keyup","keydown","keypress"];F.MouseEvents=
"click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave".split(" ");for(var j in F){var y=F[j];if(y.length)for(var q=0,A=y.length;q<A;q++)n[y[q]]=j}var m={propertychange:f},u,F=3;j=h.createElement("div");for(y=j.getElementsByTagName("i");j.innerHTML="\x3c!--[if gt IE "+ ++F+"]><i></i><![endif]--\x3e",y[0];);u=4<F?F:r;return{Na:["authenticity_token",/^__RequestVerificationToken(_.*)?$/],o:function(a,d){for(var b=0,c=a.length;b<c;b++)d(a[b])},i:function(a,d){if("function"==
typeof Array.prototype.indexOf)return Array.prototype.indexOf.call(a,d);for(var b=0,c=a.length;b<c;b++)if(a[b]===d)return b;return-1},lb:function(d,b,c){for(var e=0,s=d.length;e<s;e++)if(b.call(c,d[e]))return d[e];return a},ga:function(a,b){var c=d.a.i(a,b);0<=c&&a.splice(c,1)},Ga:function(a){a=a||[];for(var b=[],c=0,e=a.length;c<e;c++)0>d.a.i(b,a[c])&&b.push(a[c]);return b},V:function(a,d){a=a||[];for(var b=[],c=0,e=a.length;c<e;c++)b.push(d(a[c]));return b},fa:function(a,d){a=a||[];for(var b=[],
c=0,e=a.length;c<e;c++)d(a[c])&&b.push(a[c]);return b},P:function(a,d){if(d instanceof Array)a.push.apply(a,d);else for(var b=0,c=d.length;b<c;b++)a.push(d[b]);return a},extend:function(a,d){if(d)for(var b in d)d.hasOwnProperty(b)&&(a[b]=d[b]);return a},ka:function(a){for(;a.firstChild;)d.removeNode(a.firstChild)},Hb:function(a){a=d.a.L(a);for(var b=h.createElement("div"),c=0,e=a.length;c<e;c++)b.appendChild(d.A(a[c]));return b},Ia:function(a,b){for(var c=0,e=a.length,s=[];c<e;c++){var C=a[c].cloneNode(f);
s.push(b?d.A(C):C)}return s},N:function(a,b){d.a.ka(a);if(b)for(var c=0,e=b.length;c<e;c++)a.appendChild(b[c])},Ya:function(a,b){var c=a.nodeType?[a]:a;if(0<c.length){for(var e=c[0],s=e.parentNode,f=0,C=b.length;f<C;f++)s.insertBefore(b[f],e);f=0;for(C=c.length;f<C;f++)d.removeNode(c[f])}},bb:function(a,d){7>u?a.setAttribute("selected",d):a.selected=d},D:function(a){return(a||"").replace(C,"")},Rb:function(a,b){for(var c=[],e=(a||"").split(b),s=0,f=e.length;s<f;s++){var C=d.a.D(e[s]);""!==C&&c.push(C)}return c},
Ob:function(a,d){a=a||"";return d.length>a.length?b:a.substring(0,d.length)===d},tb:function(d,c){if(c.compareDocumentPosition)return 16==(c.compareDocumentPosition(d)&16);for(;d!=a;){if(d==c)return f;d=d.parentNode}return b},X:function(a){return d.a.tb(a,a.ownerDocument)},u:function(a){return a&&a.tagName&&a.tagName.toLowerCase()},n:function(a,d,e){var C=u&&m[d];if(!C&&"undefined"!=typeof g){if(s(a,d)){var h=e;e=function(a,d){var b=this.checked;d&&(this.checked=d.nb!==f);h.call(this,a);this.checked=
b}}g(a).bind(d,e)}else!C&&"function"==typeof a.addEventListener?a.addEventListener(d,e,b):"undefined"!=typeof a.attachEvent?a.attachEvent("on"+d,function(d){e.call(a,d)}):c(Error("Browser doesn't support addEventListener or attachEvent"))},Ba:function(a,d){(!a||!a.nodeType)&&c(Error("element must be a DOM node when calling triggerEvent"));if("undefined"!=typeof g){var C=[];s(a,d)&&C.push({nb:a.checked});g(a).trigger(d,C)}else"function"==typeof h.createEvent?"function"==typeof a.dispatchEvent?(C=h.createEvent(n[d]||
"HTMLEvents"),C.initEvent(d,f,f,e,0,0,0,0,0,b,b,b,b,0,a),a.dispatchEvent(C)):c(Error("The supplied element doesn't support dispatchEvent")):"undefined"!=typeof a.fireEvent?(s(a,d)&&(a.checked=a.checked!==f),a.fireEvent("on"+d)):c(Error("Browser doesn't support triggering events"))},d:function(a){return d.$(a)?a():a},ua:function(a){return d.$(a)?a.t():a},da:function(a,b,c){if(b){var e=/[\w-]+/g,s=a.className.match(e)||[];d.a.o(b.match(e),function(a){var b=d.a.i(s,a);0<=b?c||s.splice(b,1):c&&s.push(a)});
a.className=s.join(" ")}},cb:function(b,c){var e=d.a.d(c);if(e===a||e===r)e="";if(3===b.nodeType)b.data=e;else{var s=d.e.firstChild(b);!s||3!=s.nodeType||d.e.nextSibling(s)?d.e.N(b,[h.createTextNode(e)]):s.data=e;d.a.wb(b)}},ab:function(a,d){a.name=d;if(7>=u)try{a.mergeAttributes(h.createElement("<input name='"+a.name+"'/>"),b)}catch(c){}},wb:function(a){9<=u&&(a=1==a.nodeType?a:a.parentNode,a.style&&(a.style.zoom=a.style.zoom))},ub:function(a){if(9<=u){var d=a.style.width;a.style.width=0;a.style.width=
d}},Lb:function(a,b){a=d.a.d(a);b=d.a.d(b);for(var c=[],e=a;e<=b;e++)c.push(e);return c},L:function(a){for(var d=[],b=0,c=a.length;b<c;b++)d.push(a[b]);return d},Pb:6===u,Qb:7===u,Z:u,Oa:function(a,b){for(var c=d.a.L(a.getElementsByTagName("input")).concat(d.a.L(a.getElementsByTagName("textarea"))),e="string"==typeof b?function(a){return a.name===b}:function(a){return b.test(a.name)},s=[],f=c.length-1;0<=f;f--)e(c[f])&&s.push(c[f]);return s},Ib:function(b){return"string"==typeof b&&(b=d.a.D(b))?e.JSON&&
e.JSON.parse?e.JSON.parse(b):(new Function("return "+b))():a},xa:function(a,b,e){("undefined"==typeof JSON||"undefined"==typeof JSON.stringify)&&c(Error("Cannot find JSON.stringify(). Some browsers (e.g., IE < 8) don't support it natively, but you can overcome this by adding a script reference to json2.js, downloadable from http://www.json.org/json2.js"));return JSON.stringify(d.a.d(a),b,e)},Jb:function(a,b,c){c=c||{};var e=c.params||{},s=c.includeFields||this.Na,f=a;if("object"==typeof a&&"form"===
d.a.u(a))for(var f=a.action,C=s.length-1;0<=C;C--)for(var g=d.a.Oa(a,s[C]),F=g.length-1;0<=F;F--)e[g[F].name]=g[F].value;b=d.a.d(b);var n=h.createElement("form");n.style.display="none";n.action=f;n.method="post";for(var k in b)a=h.createElement("input"),a.name=k,a.value=d.a.xa(d.a.d(b[k])),n.appendChild(a);for(k in e)a=h.createElement("input"),a.name=k,a.value=e[k],n.appendChild(a);h.body.appendChild(n);c.submitter?c.submitter(n):n.submit();setTimeout(function(){n.parentNode.removeChild(n)},0)}}};
d.b("utils",d.a);d.b("utils.arrayForEach",d.a.o);d.b("utils.arrayFirst",d.a.lb);d.b("utils.arrayFilter",d.a.fa);d.b("utils.arrayGetDistinctValues",d.a.Ga);d.b("utils.arrayIndexOf",d.a.i);d.b("utils.arrayMap",d.a.V);d.b("utils.arrayPushAll",d.a.P);d.b("utils.arrayRemoveItem",d.a.ga);d.b("utils.extend",d.a.extend);d.b("utils.fieldsIncludedWithJsonPost",d.a.Na);d.b("utils.getFormFields",d.a.Oa);d.b("utils.peekObservable",d.a.ua);d.b("utils.postJson",d.a.Jb);d.b("utils.parseJson",d.a.Ib);d.b("utils.registerEventHandler",
d.a.n);d.b("utils.stringifyJson",d.a.xa);d.b("utils.range",d.a.Lb);d.b("utils.toggleDomNodeCssClass",d.a.da);d.b("utils.triggerEvent",d.a.Ba);d.b("utils.unwrapObservable",d.a.d);Function.prototype.bind||(Function.prototype.bind=function(a){var d=this,b=Array.prototype.slice.call(arguments);a=b.shift();return function(){return d.apply(a,b.concat(Array.prototype.slice.call(arguments)))}});d.a.f=new function(){var c=0,e="__ko__"+(new Date).getTime(),h={};return{get:function(a,c){var e=d.a.f.la(a,b);
return e===r?r:e[c]},set:function(a,c,e){e===r&&d.a.f.la(a,b)===r||(d.a.f.la(a,f)[c]=e)},la:function(a,d){var b=a[e];if(!b||!("null"!==b&&h[b])){if(!d)return r;b=a[e]="ko"+c++;h[b]={}}return h[b]},clear:function(d){var c=d[e];return c?(delete h[c],d[e]=a,f):b}}};d.b("utils.domData",d.a.f);d.b("utils.domData.clear",d.a.f.clear);d.a.F=new function(){function a(b,c){var e=d.a.f.get(b,h);e===r&&c&&(e=[],d.a.f.set(b,h,e));return e}function e(c){var f=a(c,b);if(f)for(var f=f.slice(0),h=0;h<f.length;h++)f[h](c);
d.a.f.clear(c);"function"==typeof g&&"function"==typeof g.cleanData&&g.cleanData([c]);if(k[c.nodeType])for(f=c.firstChild;c=f;)f=c.nextSibling,8===c.nodeType&&e(c)}var h="__ko_domNodeDisposal__"+(new Date).getTime(),n={1:f,8:f,9:f},k={1:f,9:f};return{Ca:function(d,b){"function"!=typeof b&&c(Error("Callback must be a function"));a(d,f).push(b)},Xa:function(c,e){var f=a(c,b);f&&(d.a.ga(f,e),0==f.length&&d.a.f.set(c,h,r))},A:function(a){if(n[a.nodeType]&&(e(a),k[a.nodeType])){var b=[];d.a.P(b,a.getElementsByTagName("*"));
for(var c=0,s=b.length;c<s;c++)e(b[c])}return a},removeNode:function(a){d.A(a);a.parentNode&&a.parentNode.removeChild(a)}}};d.A=d.a.F.A;d.removeNode=d.a.F.removeNode;d.b("cleanNode",d.A);d.b("removeNode",d.removeNode);d.b("utils.domNodeDisposal",d.a.F);d.b("utils.domNodeDisposal.addDisposeCallback",d.a.F.Ca);d.b("utils.domNodeDisposal.removeDisposeCallback",d.a.F.Xa);d.a.ta=function(a){var b;if("undefined"!=typeof g)if(g.parseHTML)b=g.parseHTML(a);else{if((b=g.clean([a]))&&b[0]){for(a=b[0];a.parentNode&&
11!==a.parentNode.nodeType;)a=a.parentNode;a.parentNode&&a.parentNode.removeChild(a)}}else{var c=d.a.D(a).toLowerCase();b=h.createElement("div");c=c.match(/^<(thead|tbody|tfoot)/)&&[1,"<table>","</table>"]||!c.indexOf("<tr")&&[2,"<table><tbody>","</tbody></table>"]||(!c.indexOf("<td")||!c.indexOf("<th"))&&[3,"<table><tbody><tr>","</tr></tbody></table>"]||[0,"",""];a="ignored<div>"+c[1]+a+c[2]+"</div>";for("function"==typeof e.innerShiv?b.appendChild(e.innerShiv(a)):b.innerHTML=a;c[0]--;)b=b.lastChild;
b=d.a.L(b.lastChild.childNodes)}return b};d.a.ca=function(b,c){d.a.ka(b);c=d.a.d(c);if(c!==a&&c!==r)if("string"!=typeof c&&(c=c.toString()),"undefined"!=typeof g)g(b).html(c);else for(var e=d.a.ta(c),f=0;f<e.length;f++)b.appendChild(e[f])};d.b("utils.parseHtmlFragment",d.a.ta);d.b("utils.setHtml",d.a.ca);var U={};d.s={ra:function(a){"function"!=typeof a&&c(Error("You can only pass a function to ko.memoization.memoize()"));var d=(4294967296*(1+Math.random())|0).toString(16).substring(1)+(4294967296*
(1+Math.random())|0).toString(16).substring(1);U[d]=a;return"\x3c!--[ko_memo:"+d+"]--\x3e"},hb:function(d,b){var e=U[d];e===r&&c(Error("Couldn't find any memo with ID "+d+". Perhaps it's already been unmemoized."));try{return e.apply(a,b||[]),f}finally{delete U[d]}},ib:function(a,b){var c=[];Z(a,c);for(var e=0,f=c.length;e<f;e++){var h=c[e].sb,g=[h];b&&d.a.P(g,b);d.s.hb(c[e].Fb,g);h.nodeValue="";h.parentNode&&h.parentNode.removeChild(h)}},Ua:function(d){return(d=d.match(/^\[ko_memo\:(.*?)\]$/))?d[1]:
a}};d.b("memoization",d.s);d.b("memoization.memoize",d.s.ra);d.b("memoization.unmemoize",d.s.hb);d.b("memoization.parseMemoText",d.s.Ua);d.b("memoization.unmemoizeDomNodeAndDescendants",d.s.ib);d.Ma={throttle:function(b,c){b.throttleEvaluation=c;var e=a;return d.j({read:b,write:function(a){clearTimeout(e);e=setTimeout(function(){b(a)},c)}})},notify:function(a,c){a.equalityComparer="always"==c?l(b):d.m.fn.equalityComparer;return a}};d.b("extenders",d.Ma);d.fb=function(a,b,c){this.target=a;this.ha=
b;this.rb=c;d.p(this,"dispose",this.B)};d.fb.prototype.B=function(){this.Cb=f;this.rb()};d.S=function(){this.w={};d.a.extend(this,d.S.fn);d.p(this,"subscribe",this.ya);d.p(this,"extend",this.extend);d.p(this,"getSubscriptionsCount",this.yb)};d.S.fn={ya:function(a,b,c){c=c||"change";var e=new d.fb(this,b?a.bind(b):a,function(){d.a.ga(this.w[c],e)}.bind(this));this.w[c]||(this.w[c]=[]);this.w[c].push(e);return e},notifySubscribers:function(a,b){b=b||"change";this.w[b]&&d.r.K(function(){d.a.o(this.w[b].slice(0),
function(d){d&&d.Cb!==f&&d.ha(a)})},this)},yb:function(){var a=0,d;for(d in this.w)this.w.hasOwnProperty(d)&&(a+=this.w[d].length);return a},extend:function(a){var b=this;if(a)for(var c in a){var e=d.Ma[c];"function"==typeof e&&(b=e(b,a[c]))}return b}};d.Qa=function(a){return"function"==typeof a.ya&&"function"==typeof a.notifySubscribers};d.b("subscribable",d.S);d.b("isSubscribable",d.Qa);var M=[];d.r={mb:function(a){M.push({ha:a,La:[]})},end:function(){M.pop()},Wa:function(a){d.Qa(a)||c(Error("Only subscribable things can act as dependencies"));
if(0<M.length){var b=M[M.length-1];b&&!(0<=d.a.i(b.La,a))&&(b.La.push(a),b.ha(a))}},K:function(d,b,c){try{return M.push(a),d.apply(b,c||[])}finally{M.pop()}}};var ca={undefined:f,"boolean":f,number:f,string:f};d.m=function(a){function b(){if(0<arguments.length){if(!b.equalityComparer||!b.equalityComparer(c,arguments[0]))b.H(),c=arguments[0],b.G();return this}d.r.Wa(b);return c}var c=a;d.S.call(b);b.t=function(){return c};b.G=function(){b.notifySubscribers(c)};b.H=function(){b.notifySubscribers(c,
"beforeChange")};d.a.extend(b,d.m.fn);d.p(b,"peek",b.t);d.p(b,"valueHasMutated",b.G);d.p(b,"valueWillMutate",b.H);return b};d.m.fn={equalityComparer:function(d,c){return d===a||typeof d in ca?d===c:b}};var Q=d.m.Kb="__ko_proto__";d.m.fn[Q]=d.m;d.ma=function(c,e){return c===a||c===r||c[Q]===r?b:c[Q]===e?f:d.ma(c[Q],e)};d.$=function(a){return d.ma(a,d.m)};d.Ra=function(a){return"function"==typeof a&&a[Q]===d.m||"function"==typeof a&&a[Q]===d.j&&a.zb?f:b};d.b("observable",d.m);d.b("isObservable",d.$);
d.b("isWriteableObservable",d.Ra);d.R=function(b){0==arguments.length&&(b=[]);b!==a&&b!==r&&!("length"in b)&&c(Error("The argument passed when initializing an observable array must be an array, or null, or undefined."));var e=d.m(b);d.a.extend(e,d.R.fn);return e};d.R.fn={remove:function(a){for(var d=this.t(),b=[],c="function"==typeof a?a:function(d){return d===a},e=0;e<d.length;e++){var f=d[e];c(f)&&(0===b.length&&this.H(),b.push(f),d.splice(e,1),e--)}b.length&&this.G();return b},removeAll:function(a){if(a===
r){var b=this.t(),c=b.slice(0);this.H();b.splice(0,b.length);this.G();return c}return!a?[]:this.remove(function(b){return 0<=d.a.i(a,b)})},destroy:function(a){var b=this.t(),d="function"==typeof a?a:function(b){return b===a};this.H();for(var c=b.length-1;0<=c;c--)d(b[c])&&(b[c]._destroy=f);this.G()},destroyAll:function(a){return a===r?this.destroy(l(f)):!a?[]:this.destroy(function(b){return 0<=d.a.i(a,b)})},indexOf:function(a){var b=this();return d.a.i(b,a)},replace:function(a,b){var d=this.indexOf(a);
0<=d&&(this.H(),this.t()[d]=b,this.G())}};d.a.o("pop push reverse shift sort splice unshift".split(" "),function(a){d.R.fn[a]=function(){var b=this.t();this.H();b=b[a].apply(b,arguments);this.G();return b}});d.a.o(["slice"],function(a){d.R.fn[a]=function(){var b=this();return b[a].apply(b,arguments)}});d.b("observableArray",d.R);d.j=function(e,h,g){function n(){d.a.o(w,function(a){a.B()});w=[]}function k(){var a=y.throttleEvaluation;a&&0<=a?(clearTimeout(z),z=setTimeout(j,a)):j()}function j(){if(!m)if(u&&
v())t();else{m=f;try{var a=d.a.V(w,function(a){return a.target});d.r.mb(function(b){var c;0<=(c=d.a.i(a,b))?a[c]=r:w.push(b.ya(k))});for(var c=p.call(h),e=a.length-1;0<=e;e--)a[e]&&w.splice(e,1)[0].B();u=f;y.notifySubscribers(A,"beforeChange");A=c}finally{d.r.end()}y.notifySubscribers(A);m=b;w.length||t()}}function y(){if(0<arguments.length)return"function"===typeof D?D.apply(h,arguments):c(Error("Cannot write a value to a ko.computed unless you specify a 'write' option. If you wish to read the current value, don't pass any parameters.")),
this;u||j();d.r.Wa(y);return A}function q(){return!u||0<w.length}var A,u=b,m=b,p=e;p&&"object"==typeof p?(g=p,p=g.read):(g=g||{},p||(p=g.read));"function"!=typeof p&&c(Error("Pass a function that returns the value of the ko.computed"));var D=g.write,x=g.disposeWhenNodeIsRemoved||g.W||a,v=g.disposeWhen||g.Ka||l(b),t=n,w=[],z=a;h||(h=g.owner);y.t=function(){u||j();return A};y.xb=function(){return w.length};y.zb="function"===typeof g.write;y.B=function(){t()};y.pa=q;d.S.call(y);d.a.extend(y,d.j.fn);
d.p(y,"peek",y.t);d.p(y,"dispose",y.B);d.p(y,"isActive",y.pa);d.p(y,"getDependenciesCount",y.xb);g.deferEvaluation!==f&&j();if(x&&q()){t=function(){d.a.F.Xa(x,arguments.callee);n()};d.a.F.Ca(x,t);var B=v,v=function(){return!d.a.X(x)||B()}}return y};d.Bb=function(a){return d.ma(a,d.j)};j=d.m.Kb;d.j[j]=d.m;d.j.fn={};d.j.fn[j]=d.j;d.b("dependentObservable",d.j);d.b("computed",d.j);d.b("isComputed",d.Bb);d.gb=function(a){0==arguments.length&&c(Error("When calling ko.toJS, pass the object you want to convert."));
return Y(a,function(a){for(var b=0;d.$(a)&&10>b;b++)a=a();return a})};d.toJSON=function(a,b,c){a=d.gb(a);return d.a.xa(a,b,c)};d.b("toJS",d.gb);d.b("toJSON",d.toJSON);d.k={q:function(a){switch(d.a.u(a)){case "option":return a.__ko__hasDomDataOptionValue__===f?d.a.f.get(a,d.c.options.sa):7>=d.a.Z?a.getAttributeNode("value").specified?a.value:a.text:a.value;case "select":return 0<=a.selectedIndex?d.k.q(a.options[a.selectedIndex]):r;default:return a.value}},T:function(b,c){switch(d.a.u(b)){case "option":switch(typeof c){case "string":d.a.f.set(b,
d.c.options.sa,r);"__ko__hasDomDataOptionValue__"in b&&delete b.__ko__hasDomDataOptionValue__;b.value=c;break;default:d.a.f.set(b,d.c.options.sa,c),b.__ko__hasDomDataOptionValue__=f,b.value="number"===typeof c?c:""}break;case "select":for(var e=b.options.length-1;0<=e;e--)if(d.k.q(b.options[e])==c){b.selectedIndex=e;break}break;default:if(c===a||c===r)c="";b.value=c}}};d.b("selectExtensions",d.k);d.b("selectExtensions.readValue",d.k.q);d.b("selectExtensions.writeValue",d.k.T);var da=/\@ko_token_(\d+)\@/g,
ba=["true","false"],W=/^(?:[$_a-z][$\w]*|(.+)(\.\s*[$_a-z][$\w]*|\[.+\]))$/i;d.g={Q:[],aa:function(b){var c=d.a.D(b);if(3>c.length)return[];"{"===c.charAt(0)&&(c=c.substring(1,c.length-1));b=[];for(var e=a,f,h=0;h<c.length;h++){var g=c.charAt(h);if(e===a)switch(g){case '"':case "'":case "/":e=h,f=g}else if(g==f&&"\\"!==c.charAt(h-1)){g=c.substring(e,h+1);b.push(g);var n="@ko_token_"+(b.length-1)+"@",c=c.substring(0,e)+n+c.substring(h+1),h=h-(g.length-n.length),e=a}}f=e=a;for(var k=0,j=a,h=0;h<c.length;h++){g=
c.charAt(h);if(e===a)switch(g){case "{":e=h;j=g;f="}";break;case "(":e=h;j=g;f=")";break;case "[":e=h,j=g,f="]"}g===j?k++:g===f&&(k--,0===k&&(g=c.substring(e,h+1),b.push(g),n="@ko_token_"+(b.length-1)+"@",c=c.substring(0,e)+n+c.substring(h+1),h-=g.length-n.length,e=a))}f=[];c=c.split(",");e=0;for(h=c.length;e<h;e++)k=c[e],j=k.indexOf(":"),0<j&&j<k.length-1?(g=k.substring(j+1),f.push({key:P(k.substring(0,j),b),value:P(g,b)})):f.push({unknown:P(k,b)});return f},ba:function(c){var e="string"===typeof c?
d.g.aa(c):c,f=[];c=[];for(var h,g=0;h=e[g];g++)if(0<f.length&&f.push(","),h.key){var n;a:{n=h.key;var k=d.a.D(n);switch(k.length&&k.charAt(0)){case "'":case '"':break a;default:n="'"+k+"'"}}h=h.value;f.push(n);f.push(":");f.push(h);h=d.a.D(h);0<=d.a.i(ba,d.a.D(h).toLowerCase())?h=b:(k=h.match(W),h=k===a?b:k[1]?"Object("+k[1]+")"+k[2]:h);h&&(0<c.length&&c.push(", "),c.push(n+" : function(__ko_value) { "+h+" = __ko_value; }"))}else h.unknown&&f.push(h.unknown);e=f.join("");0<c.length&&(e=e+", '_ko_property_writers' : { "+
c.join("")+" } ");return e},Eb:function(a,c){for(var e=0;e<a.length;e++)if(d.a.D(a[e].key)==c)return f;return b},ea:function(a,b,c,e,f){if(!a||!d.Ra(a)){if((a=b()._ko_property_writers)&&a[c])a[c](e)}else(!f||a.t()!==e)&&a(e)}};d.b("expressionRewriting",d.g);d.b("expressionRewriting.bindingRewriteValidators",d.g.Q);d.b("expressionRewriting.parseObjectLiteral",d.g.aa);d.b("expressionRewriting.preProcessBindings",d.g.ba);d.b("jsonExpressionRewriting",d.g);d.b("jsonExpressionRewriting.insertPropertyAccessorsIntoJson",
d.g.ba);var O="\x3c!--test--\x3e"===h.createComment("test").text,z=O?/^\x3c!--\s*ko(?:\s+(.+\s*\:[\s\S]*))?\s*--\x3e$/:/^\s*ko(?:\s+(.+\s*\:[\s\S]*))?\s*$/,R=O?/^\x3c!--\s*\/ko\s*--\x3e$/:/^\s*\/ko\s*$/,S={ul:f,ol:f};d.e={I:{},childNodes:function(a){return K(a)?E(a):a.childNodes},Y:function(a){if(K(a)){a=d.e.childNodes(a);for(var b=0,c=a.length;b<c;b++)d.removeNode(a[b])}else d.a.ka(a)},N:function(a,b){if(K(a)){d.e.Y(a);for(var c=a.nextSibling,e=0,f=b.length;e<f;e++)c.parentNode.insertBefore(b[e],
c)}else d.a.N(a,b)},Va:function(a,b){K(a)?a.parentNode.insertBefore(b,a.nextSibling):a.firstChild?a.insertBefore(b,a.firstChild):a.appendChild(b)},Pa:function(a,b,c){c?K(a)?a.parentNode.insertBefore(b,c.nextSibling):c.nextSibling?a.insertBefore(b,c.nextSibling):a.appendChild(b):d.e.Va(a,b)},firstChild:function(b){return!K(b)?b.firstChild:!b.nextSibling||L(b.nextSibling)?a:b.nextSibling},nextSibling:function(b){K(b)&&(b=w(b));return b.nextSibling&&L(b.nextSibling)?a:b.nextSibling},jb:function(b){return(b=
K(b))?b[1]:a},Ta:function(b){if(S[d.a.u(b)]){var c=b.firstChild;if(c){do if(1===c.nodeType){var e;e=c.firstChild;var h=a;if(e){do if(h)h.push(e);else if(K(e)){var g=w(e,f);g?e=g:h=[e]}else L(e)&&(h=[e]);while(e=e.nextSibling)}if(e=h){h=c.nextSibling;for(g=0;g<e.length;g++)h?b.insertBefore(e[g],h):b.appendChild(e[g])}}while(c=c.nextSibling)}}}};d.b("virtualElements",d.e);d.b("virtualElements.allowedBindings",d.e.I);d.b("virtualElements.emptyNode",d.e.Y);d.b("virtualElements.insertAfter",d.e.Pa);d.b("virtualElements.prepend",
d.e.Va);d.b("virtualElements.setDomNodeChildren",d.e.N);d.J=function(){this.Ha={}};d.a.extend(d.J.prototype,{nodeHasBindings:function(c){switch(c.nodeType){case 1:return c.getAttribute("data-bind")!=a;case 8:return d.e.jb(c)!=a;default:return b}},getBindings:function(b,d){var c=this.getBindingsString(b,d);return c?this.parseBindingsString(c,d,b):a},getBindingsString:function(b){switch(b.nodeType){case 1:return b.getAttribute("data-bind");case 8:return d.e.jb(b);default:return a}},parseBindingsString:function(a,
b,e){try{var f;if(!(f=this.Ha[a])){var h=this.Ha,g,n="with($context){with($data||{}){return{"+d.g.ba(a)+"}}}";g=new Function("$context","$element",n);f=h[a]=g}return f(b,e)}catch(k){c(Error("Unable to parse bindings.\nMessage: "+k+";\nBindings value: "+a))}}});d.J.instance=new d.J;d.b("bindingProvider",d.J);d.c={};d.z=function(a,b,c){b?(d.a.extend(this,b),this.$parentContext=b,this.$parent=b.$data,this.$parents=(b.$parents||[]).slice(0),this.$parents.unshift(this.$parent)):(this.$parents=[],this.$root=
a,this.ko=d);this.$data=a;c&&(this[c]=a)};d.z.prototype.createChildContext=function(a,b){return new d.z(a,this,b)};d.z.prototype.extend=function(a){var b=d.a.extend(new d.z,this);return d.a.extend(b,a)};d.eb=function(a,b){if(2==arguments.length)d.a.f.set(a,"__ko_bindingContext__",b);else return d.a.f.get(a,"__ko_bindingContext__")};d.Fa=function(a,b,c){1===a.nodeType&&d.e.Ta(a);return B(a,b,c,f)};d.Ea=function(a,b){(1===b.nodeType||8===b.nodeType)&&G(a,b,f)};d.Da=function(a,b){b&&1!==b.nodeType&&
8!==b.nodeType&&c(Error("ko.applyBindings: first parameter should be your view model; second parameter should be a DOM node"));b=b||e.document.body;p(a,b,f)};d.ja=function(a){switch(a.nodeType){case 1:case 8:var b=d.eb(a);if(b)return b;if(a.parentNode)return d.ja(a.parentNode)}return r};d.pb=function(a){return(a=d.ja(a))?a.$data:r};d.b("bindingHandlers",d.c);d.b("applyBindings",d.Da);d.b("applyBindingsToDescendants",d.Ea);d.b("applyBindingsToNode",d.Fa);d.b("contextFor",d.ja);d.b("dataFor",d.pb);
var V={"class":"className","for":"htmlFor"};d.c.attr={update:function(c,e){var f=d.a.d(e())||{},h;for(h in f)if("string"==typeof h){var g=d.a.d(f[h]),n=g===b||g===a||g===r;n&&c.removeAttribute(h);8>=d.a.Z&&h in V?(h=V[h],n?c.removeAttribute(h):c[h]=g):n||c.setAttribute(h,g.toString());"name"===h&&d.a.ab(c,n?"":g.toString())}}};d.c.checked={init:function(a,b,c){d.a.n(a,"click",function(){var e;if("checkbox"==a.type)e=a.checked;else if("radio"==a.type&&a.checked)e=a.value;else return;var h=b(),g=d.a.d(h);
"checkbox"==a.type&&g instanceof Array?(e=d.a.i(g,a.value),a.checked&&0>e?h.push(a.value):!a.checked&&0<=e&&h.splice(e,1)):d.g.ea(h,c,"checked",e,f)});"radio"==a.type&&!a.name&&d.c.uniqueName.init(a,l(f))},update:function(a,b){var c=d.a.d(b());"checkbox"==a.type?a.checked=c instanceof Array?0<=d.a.i(c,a.value):c:"radio"==a.type&&(a.checked=a.value==c)}};d.c.css={update:function(a,c){var e=d.a.d(c());if("object"==typeof e)for(var h in e){var g=d.a.d(e[h]);d.a.da(a,h,g)}else e=String(e||""),d.a.da(a,
a.__ko__cssValue,b),a.__ko__cssValue=e,d.a.da(a,e,f)}};d.c.enable={update:function(a,b){var c=d.a.d(b());c&&a.disabled?a.removeAttribute("disabled"):!c&&!a.disabled&&(a.disabled=f)}};d.c.disable={update:function(a,b){d.c.enable.update(a,function(){return!d.a.d(b())})}};d.c.event={init:function(a,c,e,h){var g=c()||{},n;for(n in g)(function(){var g=n;"string"==typeof g&&d.a.n(a,g,function(a){var n,s=c()[g];if(s){var k=e();try{var j=d.a.L(arguments);j.unshift(h);n=s.apply(h,j)}finally{n!==f&&(a.preventDefault?
a.preventDefault():a.returnValue=b)}k[g+"Bubble"]===b&&(a.cancelBubble=f,a.stopPropagation&&a.stopPropagation())}})})()}};d.c.foreach={Sa:function(a){return function(){var b=a(),c=d.a.ua(b);if(!c||"number"==typeof c.length)return{foreach:b,templateEngine:d.C.oa};d.a.d(b);return{foreach:c.data,as:c.as,includeDestroyed:c.includeDestroyed,afterAdd:c.afterAdd,beforeRemove:c.beforeRemove,afterRender:c.afterRender,beforeMove:c.beforeMove,afterMove:c.afterMove,templateEngine:d.C.oa}}},init:function(a,b){return d.c.template.init(a,
d.c.foreach.Sa(b))},update:function(a,b,c,e,f){return d.c.template.update(a,d.c.foreach.Sa(b),c,e,f)}};d.g.Q.foreach=b;d.e.I.foreach=f;d.c.hasfocus={init:function(c,e,h){function g(a){c.__ko_hasfocusUpdating=f;var n=c.ownerDocument;"activeElement"in n&&(a=n.activeElement===c);n=e();d.g.ea(n,h,"hasfocus",a,f);c.__ko_hasfocusUpdating=b}var n=g.bind(a,f),k=g.bind(a,b);d.a.n(c,"focus",n);d.a.n(c,"focusin",n);d.a.n(c,"blur",k);d.a.n(c,"focusout",k)},update:function(b,c){var e=d.a.d(c());b.__ko_hasfocusUpdating||
(e?b.focus():b.blur(),d.r.K(d.a.Ba,a,[b,e?"focusin":"focusout"]))}};d.c.html={init:function(){return{controlsDescendantBindings:f}},update:function(a,b){d.a.ca(a,b())}};var N="__ko_withIfBindingData";T("if");T("ifnot",b,f);T("with",f,b,function(a,b){return a.createChildContext(b)});d.c.options={update:function(a,b,e){"select"!==d.a.u(a)&&c(Error("options binding applies only to SELECT elements"));for(var g=0==a.length,n=d.a.V(d.a.fa(a.childNodes,function(a){return a.tagName&&"option"===d.a.u(a)&&
a.selected}),function(a){return d.k.q(a)||a.innerText||a.textContent}),k=a.scrollTop,j=d.a.d(b());0<a.length;)d.A(a.options[0]),a.remove(0);if(j){e=e();var y=e.optionsIncludeDestroyed;"number"!=typeof j.length&&(j=[j]);if(e.optionsCaption){var q=h.createElement("option");d.a.ca(q,e.optionsCaption);d.k.T(q,r);a.appendChild(q)}b=0;for(var A=j.length;b<A;b++){var u=j[b];if(!u||!u._destroy||y){var q=h.createElement("option"),m=function(a,b,d){var c=typeof b;return"function"==c?b(a):"string"==c?a[b]:d},
l=m(u,e.optionsValue,u);d.k.T(q,d.a.d(l));u=m(u,e.optionsText,l);d.a.cb(q,u);a.appendChild(q)}}j=a.getElementsByTagName("option");b=y=0;for(A=j.length;b<A;b++)0<=d.a.i(n,d.k.q(j[b]))&&(d.a.bb(j[b],f),y++);a.scrollTop=k;g&&"value"in e&&aa(a,d.a.ua(e.value),f);d.a.ub(a)}}};d.c.options.sa="__ko.optionValueDomData__";d.c.selectedOptions={init:function(a,b,c){d.a.n(a,"change",function(){var e=b(),f=[];d.a.o(a.getElementsByTagName("option"),function(a){a.selected&&f.push(d.k.q(a))});d.g.ea(e,c,"value",
f)})},update:function(a,b){"select"!=d.a.u(a)&&c(Error("values binding applies only to SELECT elements"));var e=d.a.d(b());e&&"number"==typeof e.length&&d.a.o(a.getElementsByTagName("option"),function(a){var b=0<=d.a.i(e,d.k.q(a));d.a.bb(a,b)})}};d.c.style={update:function(a,b){var c=d.a.d(b()||{}),e;for(e in c)if("string"==typeof e){var f=d.a.d(c[e]);a.style[e]=f||""}}};d.c.submit={init:function(a,e,h,g){"function"!=typeof e()&&c(Error("The value for a submit binding must be a function"));d.a.n(a,
"submit",function(d){var c,h=e();try{c=h.call(g,a)}finally{c!==f&&(d.preventDefault?d.preventDefault():d.returnValue=b)}})}};d.c.text={update:function(a,b){d.a.cb(a,b())}};d.e.I.text=f;d.c.uniqueName={init:function(a,b){if(b()){var c="ko_unique_"+ ++d.c.uniqueName.ob;d.a.ab(a,c)}}};d.c.uniqueName.ob=0;d.c.value={init:function(a,c,e){function h(){k=b;var f=c(),g=d.k.q(a);d.g.ea(f,e,"value",g)}var g=["change"],n=e().valueUpdate,k=b;n&&("string"==typeof n&&(n=[n]),d.a.P(g,n),g=d.a.Ga(g));if(d.a.Z&&"input"==
a.tagName.toLowerCase()&&("text"==a.type&&"off"!=a.autocomplete&&(!a.form||"off"!=a.form.autocomplete))&&-1==d.a.i(g,"propertychange"))d.a.n(a,"propertychange",function(){k=f}),d.a.n(a,"blur",function(){k&&h()});d.a.o(g,function(b){var c=h;d.a.Ob(b,"after")&&(c=function(){setTimeout(h,0)},b=b.substring(5));d.a.n(a,b,c)})},update:function(a,c){var e="select"===d.a.u(a),h=d.a.d(c()),g=d.k.q(a),n=h!=g;0===h&&0!==g&&"0"!==g&&(n=f);n&&(g=function(){d.k.T(a,h)},g(),e&&setTimeout(g,0));e&&0<a.length&&aa(a,
h,b)}};d.c.visible={update:function(a,b){var c=d.a.d(b()),e="none"!=a.style.display;c&&!e?a.style.display="":!c&&e&&(a.style.display="none")}};d.c.click={init:function(a,b,c,e){return d.c.event.init.call(this,a,function(){var a={};a.click=b();return a},c,e)}};d.v=function(){};d.v.prototype.renderTemplateSource=function(){c(Error("Override renderTemplateSource"))};d.v.prototype.createJavaScriptEvaluatorBlock=function(){c(Error("Override createJavaScriptEvaluatorBlock"))};d.v.prototype.makeTemplateSource=
function(a,b){if("string"==typeof a){b=b||h;var e=b.getElementById(a);e||c(Error("Cannot find template with ID "+a));return new d.l.h(e)}if(1==a.nodeType||8==a.nodeType)return new d.l.O(a);c(Error("Unknown template type: "+a))};d.v.prototype.renderTemplate=function(a,b,d,c){a=this.makeTemplateSource(a,c);return this.renderTemplateSource(a,b,d)};d.v.prototype.isTemplateRewritten=function(a,d){return this.allowTemplateRewriting===b?f:this.makeTemplateSource(a,d).data("isRewritten")};d.v.prototype.rewriteTemplate=
function(a,b,d){a=this.makeTemplateSource(a,d);b=b(a.text());a.text(b);a.data("isRewritten",f)};d.b("templateEngine",d.v);var n=/(<[a-z]+\d*(\s+(?!data-bind=)[a-z0-9\-]+(=(\"[^\"]*\"|\'[^\']*\'))?)*\s+)data-bind=(["'])([\s\S]*?)\5/gi,y=/\x3c!--\s*ko\b\s*([\s\S]*?)\s*--\x3e/g;d.za={vb:function(a,b,c){b.isTemplateRewritten(a,c)||b.rewriteTemplate(a,function(a){return d.za.Gb(a,b)},c)},Gb:function(a,b){return a.replace(n,function(a,d,c,e,f,h,g){return m(g,d,b)}).replace(y,function(a,d){return m(d,"\x3c!-- ko --\x3e",
b)})},kb:function(a){return d.s.ra(function(b,c){b.nextSibling&&d.Fa(b.nextSibling,a,c)})}};d.b("__tr_ambtns",d.za.kb);d.l={};d.l.h=function(a){this.h=a};d.l.h.prototype.text=function(){var a=d.a.u(this.h),a="script"===a?"text":"textarea"===a?"value":"innerHTML";if(0==arguments.length)return this.h[a];var b=arguments[0];"innerHTML"===a?d.a.ca(this.h,b):this.h[a]=b};d.l.h.prototype.data=function(a){if(1===arguments.length)return d.a.f.get(this.h,"templateSourceData_"+a);d.a.f.set(this.h,"templateSourceData_"+
a,arguments[1])};d.l.O=function(a){this.h=a};d.l.O.prototype=new d.l.h;d.l.O.prototype.text=function(){if(0==arguments.length){var a=d.a.f.get(this.h,"__ko_anon_template__")||{};a.Aa===r&&a.ia&&(a.Aa=a.ia.innerHTML);return a.Aa}d.a.f.set(this.h,"__ko_anon_template__",{Aa:arguments[0]})};d.l.h.prototype.nodes=function(){if(0==arguments.length)return(d.a.f.get(this.h,"__ko_anon_template__")||{}).ia;d.a.f.set(this.h,"__ko_anon_template__",{ia:arguments[0]})};d.b("templateSources",d.l);d.b("templateSources.domElement",
d.l.h);d.b("templateSources.anonymousTemplate",d.l.O);var A;d.wa=function(a){a!=r&&!(a instanceof d.v)&&c(Error("templateEngine must inherit from ko.templateEngine"));A=a};d.va=function(b,e,f,h,g){f=f||{};(f.templateEngine||A)==r&&c(Error("Set a template engine before calling renderTemplate"));g=g||"replaceChildren";if(h){var n=I(h);return d.j(function(){var a=e&&e instanceof d.z?e:new d.z(d.a.d(e)),c="function"==typeof b?b(a.$data,a):b,a=J(h,g,c,a,f);"replaceNode"==g&&(h=a,n=I(h))},a,{Ka:function(){return!n||
!d.a.X(n)},W:n&&"replaceNode"==g?n.parentNode:n})}return d.s.ra(function(a){d.va(b,e,f,a,"replaceNode")})};d.Mb=function(b,c,e,f,h){function g(a,b){t(b,k);e.afterRender&&e.afterRender(b,a)}function n(c,f){k=h.createChildContext(d.a.d(c),e.as);k.$index=f;var g="function"==typeof b?b(c,k):b;return J(a,"ignoreTargetNode",g,k,e)}var k;return d.j(function(){var b=d.a.d(c)||[];"undefined"==typeof b.length&&(b=[b]);b=d.a.fa(b,function(b){return e.includeDestroyed||b===r||b===a||!d.a.d(b._destroy)});d.r.K(d.a.$a,
a,[f,b,n,e,g])},a,{W:f})};d.c.template={init:function(a,b){var c=d.a.d(b());if("string"!=typeof c&&!c.name&&(1==a.nodeType||8==a.nodeType))c=1==a.nodeType?a.childNodes:d.e.childNodes(a),c=d.a.Hb(c),(new d.l.O(a)).nodes(c);return{controlsDescendantBindings:f}},update:function(b,c,e,h,g){c=d.a.d(c());e={};h=f;var n,k=a;"string"!=typeof c&&(e=c,c=e.name,"if"in e&&(h=d.a.d(e["if"])),h&&"ifnot"in e&&(h=!d.a.d(e.ifnot)),n=d.a.d(e.data));"foreach"in e?k=d.Mb(c||b,h&&e.foreach||[],e,b,g):h?(g="data"in e?
g.createChildContext(n,e.as):g,k=d.va(c||b,g,e,b)):d.e.Y(b);g=k;(n=d.a.f.get(b,"__ko__templateComputedDomDataKey__"))&&"function"==typeof n.B&&n.B();d.a.f.set(b,"__ko__templateComputedDomDataKey__",g&&g.pa()?g:r)}};d.g.Q.template=function(b){b=d.g.aa(b);return 1==b.length&&b[0].unknown||d.g.Eb(b,"name")?a:"This template engine does not support anonymous templates nested within its templates"};d.e.I.template=f;d.b("setTemplateEngine",d.wa);d.b("renderTemplate",d.va);d.a.Ja=function(a,b,d){a=a||[];
b=b||[];return a.length<=b.length?x(a,b,"added","deleted",d):x(b,a,"deleted","added",d)};d.b("utils.compareArrays",d.a.Ja);d.a.$a=function(a,b,c,e,h){function g(a,b){t=j[b];l!==b&&(v[a]=t);t.na(l++);D(t.M);A.push(t);x.push(t)}function n(a,b){if(a)for(var c=0,e=b.length;c<e;c++)b[c]&&d.a.o(b[c].M,function(d){a(d,c,b[c].U)})}b=b||[];e=e||{};var k=d.a.f.get(a,"setDomNodeChildrenFromArrayMapping_lastMappingResult")===r,j=d.a.f.get(a,"setDomNodeChildrenFromArrayMapping_lastMappingResult")||[],y=d.a.V(j,
function(a){return a.U}),q=d.a.Ja(y,b),A=[],m=0,l=0,p=[],x=[];b=[];for(var v=[],y=[],t,w=0,z,B;z=q[w];w++)switch(B=z.moved,z.status){case "deleted":B===r&&(t=j[m],t.j&&t.j.B(),p.push.apply(p,D(t.M)),e.beforeRemove&&(b[w]=t,x.push(t)));m++;break;case "retained":g(w,m++);break;case "added":B!==r?g(w,B):(t={U:z.value,na:d.m(l++)},A.push(t),x.push(t),k||(y[w]=t))}n(e.beforeMove,v);d.a.o(p,e.beforeRemove?d.A:d.removeNode);for(var w=0,k=d.e.firstChild(a),E;t=x[w];w++){t.M||d.a.extend(t,u(a,c,t.U,h,t.na));
for(m=0;q=t.M[m];k=q.nextSibling,E=q,m++)q!==k&&d.e.Pa(a,q,E);!t.Ab&&h&&(h(t.U,t.M,t.na),t.Ab=f)}n(e.beforeRemove,b);n(e.afterMove,v);n(e.afterAdd,y);d.a.f.set(a,"setDomNodeChildrenFromArrayMapping_lastMappingResult",A)};d.b("utils.setDomNodeChildrenFromArrayMapping",d.a.$a);d.C=function(){this.allowTemplateRewriting=b};d.C.prototype=new d.v;d.C.prototype.renderTemplateSource=function(b){var c=!(9>d.a.Z)&&b.nodes?b.nodes():a;if(c)return d.a.L(c.cloneNode(f).childNodes);b=b.text();return d.a.ta(b)};
d.C.oa=new d.C;d.wa(d.C.oa);d.b("nativeTemplateEngine",d.C);d.qa=function(){var b=this.Db=function(){if("undefined"==typeof g||!g.tmpl)return 0;try{if(0<=g.tmpl.tag.tmpl.open.toString().indexOf("__"))return 2}catch(a){}return 1}();this.renderTemplateSource=function(d,e,f){f=f||{};2>b&&c(Error("Your version of jQuery.tmpl is too old. Please upgrade to jQuery.tmpl 1.0.0pre or later."));var n=d.data("precompiled");n||(n=d.text()||"",n=g.template(a,"{{ko_with $item.koBindingContext}}"+n+"{{/ko_with}}"),
d.data("precompiled",n));d=[e.$data];e=g.extend({koBindingContext:e},f.templateOptions);e=g.tmpl(n,d,e);e.appendTo(h.createElement("div"));g.fragments={};return e};this.createJavaScriptEvaluatorBlock=function(a){return"{{ko_code ((function() { return "+a+" })()) }}"};this.addTemplate=function(a,b){h.write("<script type='text/html' id='"+a+"'>"+b+"\x3c/script>")};0<b&&(g.tmpl.tag.ko_code={open:"__.push($1 || '');"},g.tmpl.tag.ko_with={open:"with($1) {",close:"} "})};d.qa.prototype=new d.v;j=new d.qa;
0<j.Db&&d.wa(j);d.b("jqueryTmplTemplateEngine",d.qa)}var f=!0,a=null,b=!1,e=window,h=document,k=navigator,g=window.jQuery,r=void 0;"function"===typeof require&&"object"===typeof exports&&"object"===typeof module?j(module.exports||exports):"function"===typeof define&&define.amd?define(["exports"],j):j(e.ko={});f})();
(function(c){function l(a,b){return function(d){return k(a.call(this,d),b)}}function j(a){return function(b){return this.lang().ordinal(a.call(this,b))}}function f(){}function a(a){e(this,a)}function b(a){var b=this._data={},d=a.years||a.year||a.y||0,c=a.months||a.month||a.M||0,e=a.weeks||a.week||a.w||0,f=a.days||a.day||a.d||0,g=a.hours||a.hour||a.h||0,k=a.minutes||a.minute||a.m||0,j=a.seconds||a.second||a.s||0;a=a.milliseconds||a.millisecond||a.ms||0;this._milliseconds=a+1E3*j+6E4*k+36E5*g;this._days=
f+7*e;this._months=c+12*d;b.milliseconds=a%1E3;j+=h(a/1E3);b.seconds=j%60;k+=h(j/60);b.minutes=k%60;g+=h(k/60);b.hours=g%24;f+=h(g/24);f+=7*e;b.days=f%30;c+=h(f/30);b.months=c%12;d+=h(c/12);b.years=d}function e(a,b){for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d]);return a}function h(a){return 0>a?Math.ceil(a):Math.floor(a)}function k(a,b){for(var d=a+"";d.length<b;)d="0"+d;return d}function g(a,b,d){var c=b._milliseconds,e=b._days;b=b._months;var f;c&&a._d.setTime(+a+c*d);e&&a.date(a.date()+e*d);
b&&(f=a.date(),a.date(1).month(a.month()+b*d).date(Math.min(f,a.daysInMonth())))}function r(a,b){var d=Math.min(a.length,b.length),c=Math.abs(a.length-b.length),e=0,f;for(f=0;f<d;f++)~~a[f]!==~~b[f]&&e++;return e+c}function q(a){return a?(!E[a]&&L&&require("./lang/"+a),E[a]):p.fn._lang}function u(a){switch(a){case "DDDD":return T;case "YYYY":return aa;case "YYYYY":return d;case "S":case "SS":case "SSS":case "DDD":return Z;case "MMM":case "MMMM":case "dd":case "ddd":case "dddd":case "a":case "A":return U;
case "X":return Q;case "Z":case "ZZ":return M;case "T":return ca;case "MM":case "DD":case "YY":case "HH":case "hh":case "mm":case "ss":case "M":case "D":case "d":case "H":case "h":case "m":case "s":return Y;default:return RegExp(a.replace("\\",""))}}function D(a){var b,d=[];if(!a._d){for(b=0;7>b;b++)a._a[b]=d[b]=null==a._a[b]?2===b?1:0:a._a[b];d[3]+=a._tzh||0;d[4]+=a._tzm||0;b=new Date(0);a._useUTC?(b.setUTCFullYear(d[0],d[1],d[2]),b.setUTCHours(d[3],d[4],d[5],d[6])):(b.setFullYear(d[0],d[1],d[2]),
b.setHours(d[3],d[4],d[5],d[6]));a._d=b}}function x(a){var b=a._f.match(P),d=a._i,c,e;a._a=[];for(c=0;c<b.length;c++)if((e=(u(b[c]).exec(d)||[])[0])&&(d=d.slice(d.indexOf(e)+e.length)),N[b[c]]){var f=a,h=void 0,g=f._a;switch(b[c]){case "M":case "MM":g[1]=null==e?0:~~e-1;break;case "MMM":case "MMMM":h=q(f._l).monthsParse(e);null!=h?g[1]=h:f._isValid=!1;break;case "D":case "DD":case "DDD":case "DDDD":null!=e&&(g[2]=~~e);break;case "YY":g[0]=~~e+(68<~~e?1900:2E3);break;case "YYYY":case "YYYYY":g[0]=
~~e;break;case "a":case "A":f._isPm="pm"===(e+"").toLowerCase();break;case "H":case "HH":case "h":case "hh":g[3]=~~e;break;case "m":case "mm":g[4]=~~e;break;case "s":case "ss":g[5]=~~e;break;case "S":case "SS":case "SSS":g[6]=~~(1E3*("0."+e));break;case "X":f._d=new Date(1E3*parseFloat(e));break;case "Z":case "ZZ":f._useUTC=!0,(h=(e+"").match(W))&&h[1]&&(f._tzh=~~h[1]),h&&h[2]&&(f._tzm=~~h[2]),h&&"+"===h[0]&&(f._tzh=-f._tzh,f._tzm=-f._tzm)}null==e&&(f._isValid=!1)}a._isPm&&12>a._a[3]&&(a._a[3]+=12);
!1===a._isPm&&12===a._a[3]&&(a._a[3]=0);D(a)}function J(a,b,d,c,e){return e.relativeTime(b||1,!!d,a,c)}function I(a,b,d){b=d-b;d-=a.day();return d>b&&(d-=7),d<b-7&&(d+=7),Math.ceil(p(a).add("d",d).dayOfYear()/7)}function t(b){var d=b._i,f=b._f;if(null===d||""===d)b=null;else{"string"==typeof d&&(b._i=d=q().preparse(d));if(p.isMoment(d))b=e({},d),b._d=new Date(+d._d);else if(f)if("[object Array]"===Object.prototype.toString.call(f)){for(var d=b,h,g,k=99;d._f.length;){h=e({},d);h._f=d._f.pop();x(h);
f=new a(h);if(f.isValid()){g=f;break}h=r(h._a,f.toArray());h<k&&(k=h,g=f)}e(d,g)}else x(b);else if(g=b,d=g._i,f=K.exec(d),d===c)g._d=new Date;else if(f)g._d=new Date(+f[1]);else if("string"==typeof d)if(f=g._i,da.exec(f)){g._f="YYYY-MM-DDT";for(d=0;4>d;d++)if(ba[d][1].exec(f)){g._f+=ba[d][0];break}M.exec(f)&&(g._f+=" Z");x(g)}else g._d=new Date(f);else"[object Array]"===Object.prototype.toString.call(d)?(g._a=d.slice(0),D(g)):g._d=d instanceof Date?new Date(+d):new Date(d);b=new a(b)}return b}function v(a,
b){p.fn[a]=p.fn[a+"s"]=function(a){var d=this._isUTC?"UTC":"";return null!=a?(this._d["set"+d+b](a),this):this._d["get"+d+b]()}}function m(a){p.duration.fn[a]=function(){return this._data[a]}}function B(a,b){p.duration.fn["as"+a]=function(){return+this/b}}for(var p,G=Math.round,w,E={},L="undefined"!=typeof module&&module.exports,K=/^\/?Date\((\-?\d+)/i,P=/(\[[^\[]*\])|(\\)?(Mo|MM?M?M?|Do|DDDo|DD?D?D?|ddd?d?|do?|w[o|w]?|W[o|W]?|YYYYY|YYYY|YY|a|A|hh?|HH?|mm?|ss?|SS?S?|X|zz?|ZZ?|.)/g,X=/(\[[^\[]*\])|(\\)?(LT|LL?L?L?|l{1,4})/g,
Y=/\d\d?/,Z=/\d{1,3}/,T=/\d{3}/,aa=/\d{1,4}/,d=/[+\-]?\d{1,6}/,U=/[0-9]*[a-z\u00A0-\u05FF\u0700-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+|[\u0600-\u06FF]+\s*?[\u0600-\u06FF]+/i,M=/Z|[\+\-]\d\d:?\d\d/i,ca=/T/i,Q=/[\+\-]?\d+(\.\d{1,3})?/,da=/^\s*\d{4}-\d\d-\d\d((T| )(\d\d(:\d\d(:\d\d(\.\d\d?\d?)?)?)?)?([\+\-]\d\d:?\d\d)?)?/,ba=[["HH:mm:ss.S",/(T| )\d\d:\d\d:\d\d\.\d{1,3}/],["HH:mm:ss",/(T| )\d\d:\d\d:\d\d/],["HH:mm",/(T| )\d\d:\d\d/],["HH",/(T| )\d\d/]],W=/([\+\-]|\d\d)/gi,O="Month Date Hours Minutes Seconds Milliseconds".split(" "),
z={Milliseconds:1,Seconds:1E3,Minutes:6E4,Hours:36E5,Days:864E5,Months:2592E6,Years:31536E6},R={},S="DDD w W M D d".split(" "),V="MDHhmswW".split(""),N={M:function(){return this.month()+1},MMM:function(a){return this.lang().monthsShort(this,a)},MMMM:function(a){return this.lang().months(this,a)},D:function(){return this.date()},DDD:function(){return this.dayOfYear()},d:function(){return this.day()},dd:function(a){return this.lang().weekdaysMin(this,a)},ddd:function(a){return this.lang().weekdaysShort(this,
a)},dddd:function(a){return this.lang().weekdays(this,a)},w:function(){return this.week()},W:function(){return this.isoWeek()},YY:function(){return k(this.year()%100,2)},YYYY:function(){return k(this.year(),4)},YYYYY:function(){return k(this.year(),5)},a:function(){return this.lang().meridiem(this.hours(),this.minutes(),!0)},A:function(){return this.lang().meridiem(this.hours(),this.minutes(),!1)},H:function(){return this.hours()},h:function(){return this.hours()%12||12},m:function(){return this.minutes()},
s:function(){return this.seconds()},S:function(){return~~(this.milliseconds()/100)},SS:function(){return k(~~(this.milliseconds()/10),2)},SSS:function(){return k(this.milliseconds(),3)},Z:function(){var a=-this.zone();return 0>a&&(a=-a),"+"+k(~~(a/60),2)+":"+k(~~a%60,2)},ZZ:function(){var a=-this.zone();return 0>a&&(a=-a),"+"+k(~~(10*a/6),4)},X:function(){return this.unix()}};S.length;)w=S.pop(),N[w+"o"]=j(N[w]);for(;V.length;)w=V.pop(),N[w+w]=l(N[w],2);N.DDDD=l(N.DDD,3);f.prototype={set:function(a){var b,
d;for(d in a)b=a[d],"function"==typeof b?this[d]=b:this["_"+d]=b},_months:"January February March April May June July August September October November December".split(" "),months:function(a){return this._months[a.month()]},_monthsShort:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),monthsShort:function(a){return this._monthsShort[a.month()]},monthsParse:function(a){var b,d,c;this._monthsParse||(this._monthsParse=[]);for(b=0;12>b;b++)if(this._monthsParse[b]||(d=p([2E3,b]),c="^"+this.months(d,
"")+"|^"+this.monthsShort(d,""),this._monthsParse[b]=RegExp(c.replace(".",""),"i")),this._monthsParse[b].test(a))return b},_weekdays:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),weekdays:function(a){return this._weekdays[a.day()]},_weekdaysShort:"Sun Mon Tue Wed Thu Fri Sat".split(" "),weekdaysShort:function(a){return this._weekdaysShort[a.day()]},_weekdaysMin:"Su Mo Tu We Th Fr Sa".split(" "),weekdaysMin:function(a){return this._weekdaysMin[a.day()]},_longDateFormat:{LT:"h:mm A",
L:"MM/DD/YYYY",LL:"MMMM D YYYY",LLL:"MMMM D YYYY LT",LLLL:"dddd, MMMM D YYYY LT"},longDateFormat:function(a){var b=this._longDateFormat[a];return!b&&this._longDateFormat[a.toUpperCase()]&&(b=this._longDateFormat[a.toUpperCase()].replace(/MMMM|MM|DD|dddd/g,function(a){return a.slice(1)}),this._longDateFormat[a]=b),b},meridiem:function(a,b,d){return 11<a?d?"pm":"PM":d?"am":"AM"},_calendar:{sameDay:"[Today at] LT",nextDay:"[Tomorrow at] LT",nextWeek:"dddd [at] LT",lastDay:"[Yesterday at] LT",lastWeek:"[last] dddd [at] LT",
sameElse:"L"},calendar:function(a,b){var d=this._calendar[a];return"function"==typeof d?d.apply(b):d},_relativeTime:{future:"in %s",past:"%s ago",s:"a few seconds",m:"a minute",mm:"%d minutes",h:"an hour",hh:"%d hours",d:"a day",dd:"%d days",M:"a month",MM:"%d months",y:"a year",yy:"%d years"},relativeTime:function(a,b,d,c){var e=this._relativeTime[d];return"function"==typeof e?e(a,b,d,c):e.replace(/%d/i,a)},pastFuture:function(a,b){var d=this._relativeTime[0<a?"future":"past"];return"function"==
typeof d?d(b):d.replace(/%s/i,b)},ordinal:function(a){return this._ordinal.replace("%d",a)},_ordinal:"%d",preparse:function(a){return a},postformat:function(a){return a},week:function(a){return I(a,this._week.dow,this._week.doy)},_week:{dow:0,doy:6}};p=function(a,b,d){return t({_i:a,_f:b,_l:d,_isUTC:!1})};p.utc=function(a,b,d){return t({_useUTC:!0,_isUTC:!0,_l:d,_i:a,_f:b})};p.unix=function(a){return p(1E3*a)};p.duration=function(a,d){var c=p.isDuration(a),e="number"==typeof a,f=c?a._data:e?{}:a,
h;return e&&(d?f[d]=a:f.milliseconds=a),h=new b(f),c&&a.hasOwnProperty("_lang")&&(h._lang=a._lang),h};p.version="2.0.0";p.defaultFormat="YYYY-MM-DDTHH:mm:ssZ";p.lang=function(a,b){if(!a)return p.fn._lang._abbr;b?(b.abbr=a,E[a]||(E[a]=new f),E[a].set(b)):E[a]||q(a);p.duration.fn._lang=p.fn._lang=q(a)};p.langData=function(a){return a&&a._lang&&a._lang._abbr&&(a=a._lang._abbr),q(a)};p.isMoment=function(b){return b instanceof a};p.isDuration=function(a){return a instanceof b};p.fn=a.prototype={clone:function(){return p(this)},
valueOf:function(){return+this._d},unix:function(){return Math.floor(+this._d/1E3)},toString:function(){return this.format("ddd MMM DD YYYY HH:mm:ss [GMT]ZZ")},toDate:function(){return this._d},toJSON:function(){return p.utc(this).format("YYYY-MM-DD[T]HH:mm:ss.SSS[Z]")},toArray:function(){return[this.year(),this.month(),this.date(),this.hours(),this.minutes(),this.seconds(),this.milliseconds()]},isValid:function(){return null==this._isValid&&(this._a?this._isValid=!r(this._a,(this._isUTC?p.utc(this._a):
p(this._a)).toArray()):this._isValid=!isNaN(this._d.getTime())),!!this._isValid},utc:function(){return this._isUTC=!0,this},local:function(){return this._isUTC=!1,this},format:function(a){var b=this;a=a||p.defaultFormat;for(var d=function(a){return b.lang().longDateFormat(a)||a},c=5;c--&&X.test(a);)a=a.replace(X,d);if(!R[a]){var e=d=a,f=e.match(P),h,g;h=0;for(g=f.length;h<g;h++)N[f[h]]?f[h]=N[f[h]]:f[h]=f[h].match(/\[.*\]/)?f[h].replace(/^\[|\]$/g,""):f[h].replace(/\\/g,"");R[d]=function(a){var b=
"";for(h=0;h<g;h++)b+="function"==typeof f[h].call?f[h].call(a,e):f[h];return b}}a=R[a](b);return this.lang().postformat(a)},add:function(a,b){var d;return"string"==typeof a?d=p.duration(+b,a):d=p.duration(a,b),g(this,d,1),this},subtract:function(a,b){var d;return"string"==typeof a?d=p.duration(+b,a):d=p.duration(a,b),g(this,d,-1),this},diff:function(a,b,d){a=this._isUTC?p(a).utc():p(a).local();var c=6E4*(this.zone()-a.zone()),e,f;return b&&(b=b.replace(/s$/,"")),"year"===b||"month"===b?(e=432E5*
(this.daysInMonth()+a.daysInMonth()),f=12*(this.year()-a.year())+(this.month()-a.month()),f+=(this-p(this).startOf("month")-(a-p(a).startOf("month")))/e,"year"===b&&(f/=12)):(e=this-a-c,f="second"===b?e/1E3:"minute"===b?e/6E4:"hour"===b?e/36E5:"day"===b?e/864E5:"week"===b?e/6048E5:e),d?f:h(f)},from:function(a,b){return p.duration(this.diff(a)).lang(this.lang()._abbr).humanize(!b)},fromNow:function(a){return this.from(p(),a)},calendar:function(){var a=this.diff(p().startOf("day"),"days",!0);return this.format(this.lang().calendar(-6>
a?"sameElse":-1>a?"lastWeek":0>a?"lastDay":1>a?"sameDay":2>a?"nextDay":7>a?"nextWeek":"sameElse",this))},isLeapYear:function(){var a=this.year();return 0===a%4&&0!==a%100||0===a%400},isDST:function(){return this.zone()<p([this.year()]).zone()||this.zone()<p([this.year(),5]).zone()},day:function(a){var b=this._isUTC?this._d.getUTCDay():this._d.getDay();return null==a?b:this.add({d:a-b})},startOf:function(a){a=a.replace(/s$/,"");switch(a){case "year":this.month(0);case "month":this.date(1);case "week":case "day":this.hours(0);
case "hour":this.minutes(0);case "minute":this.seconds(0);case "second":this.milliseconds(0)}return"week"===a&&this.day(0),this},endOf:function(a){return this.startOf(a).add(a.replace(/s?$/,"s"),1).subtract("ms",1)},isAfter:function(a,b){return b="undefined"!=typeof b?b:"millisecond",+this.clone().startOf(b)>+p(a).startOf(b)},isBefore:function(a,b){return b="undefined"!=typeof b?b:"millisecond",+this.clone().startOf(b)<+p(a).startOf(b)},isSame:function(a,b){return b="undefined"!=typeof b?b:"millisecond",
+this.clone().startOf(b)===+p(a).startOf(b)},zone:function(){return this._isUTC?0:this._d.getTimezoneOffset()},daysInMonth:function(){return p.utc([this.year(),this.month()+1,0]).date()},dayOfYear:function(a){var b=G((p(this).startOf("day")-p(this).startOf("year"))/864E5)+1;return null==a?b:this.add("d",a-b)},isoWeek:function(a){var b=I(this,1,4);return null==a?b:this.add("d",7*(a-b))},week:function(a){var b=this.lang().week(this);return null==a?b:this.add("d",7*(a-b))},lang:function(a){return a===
c?this._lang:(this._lang=q(a),this)}};for(w=0;w<O.length;w++)v(O[w].toLowerCase().replace(/s$/,""),O[w]);v("year","FullYear");p.fn.days=p.fn.day;p.fn.weeks=p.fn.week;p.fn.isoWeeks=p.fn.isoWeek;p.duration.fn=b.prototype={weeks:function(){return h(this.days()/7)},valueOf:function(){return this._milliseconds+864E5*this._days+2592E6*this._months},humanize:function(a){var b=+this,d;d=!a;var c=this.lang(),e=G(Math.abs(b)/1E3),f=G(e/60),h=G(f/60),g=G(h/24),k=G(g/365),e=45>e&&["s",e]||1===f&&["m"]||45>f&&
["mm",f]||1===h&&["h"]||22>h&&["hh",h]||1===g&&["d"]||25>=g&&["dd",g]||45>=g&&["M"]||345>g&&["MM",G(g/30)]||1===k&&["y"]||["yy",k];d=(e[2]=d,e[3]=0<b,e[4]=c,J.apply({},e));return a&&(d=this.lang().pastFuture(b,d)),this.lang().postformat(d)},lang:p.fn.lang};for(w in z)z.hasOwnProperty(w)&&(B(w,z[w]),m(w.toLowerCase()));B("Weeks",6048E5);p.lang("en",{ordinal:function(a){var b=a%10;return a+(1===~~(a%100/10)?"th":1===b?"st":2===b?"nd":3===b?"rd":"th")}});L&&(module.exports=p);"undefined"==typeof ender&&
(this.moment=p);"function"==typeof define&&define.amd&&define("moment",[],function(){return p})}).call(this);var libFuncName=null;if("undefined"==typeof jQuery&&"undefined"==typeof Zepto&&"function"==typeof $)libFuncName=$;else if("function"==typeof jQuery)libFuncName=jQuery;else{if("function"!=typeof Zepto)throw new TypeError;libFuncName=Zepto};